### ISSUE TITLE
Cache bcsymbolmap files

### ISSUE THREAD

**Issue by HKisd** [blender/Rome#100]
#### Enhancement Suggestion

Cache bcsymbolmap files

**Steps which explain the enhancement**

1. Upload should upload bcsymbolmap files of framework
2. Download should download bcsymbolmap files framework

**Current and suggested behavior**

Currently bcsymbolmap files seem to be ignored by Rome
There should be a zip archive also for bcsymbolmap files

Carthage archive command makes a zip file which contains also bcsymbolmap files, so that might be useful reference:

    $ carthage archive Alamofire
    *** Found Carthage/Build/iOS/Alamofire.framework
    *** Found Carthage/Build/iOS/Alamofire.framework.dSYM
    *** Found Carthage/Build/iOS/7246C4C8-54CB-36B4-814F-E6E8B595EA74.bcsymbolmap
    *** Found Carthage/Build/iOS/0F93FE26-5586-3A7C-8449-2DB18861AF00.bcsymbolmap
    *** Found Carthage/Build/iOS/17132633-DF81-32A0-B7FE-BB4101B1C246.bcsymbolmap
    *** Found Carthage/Build/iOS/A48FAE2B-3B09-3F27-A4FB-BE81C0FFE75B.bcsymbolmap
    *** Created Alamofire.framework.zip

**Why would the enhancement be useful to most users**

bcsymbolmap is required for uploading bitcode containing apps to App Store

**Rome version:** 0.12.0.31
**OS and version:** macOS 10.12.6

**Comment by blender** [comment]
I see. Any idea how the bcsymbolmap is paired to the framework?

**Comment by HKisd** [comment]
Carthage uses this command to find the UUIDs for bcsymbolmap files:

/usr/bin/xcrun dwarfdump --uuid Alamofire.framework/Alamofire

**Comment by blender** [comment]
You can follow the development there: https://github.com/blender/Rome/pull/101

**Comment by blender** [comment]
@HKisd please try https://github.com/blender/Rome/releases/tag/v0.13.0.32

This one actually took me some time to do.

If no bugs are reported I will promote it to a full release. Please let me know one you have tried.

**Comment by blender** [comment]
@HKisd did you have the chance to it out?

**Comment by blender** [comment]
@HKisd any feedback? I'll make a full release in the next few days :)

**Comment by blender** [comment]
Done!
