### ISSUE TITLE
IgnoreMap should be ignored when listing rome missing dependencies

### ISSUE THREAD

**Issue by c0diq** [blender/Rome#107]
#### Enhancement Suggestion

   When using `rome list --missing`, the projects listed under [IgnoreMap] are skipped thus it is not possible to use it to "checkout" or "bootstrap" dependencies that are not stored in Rome. For example:
"rome list --missing --platform ios | awk '{print $1}' | xargs carthage bootstrap --platform ios --cache-builds"

    **Current and suggested behavior**

    Add a parameter to allow returning ignored projects from "rome list"

**Comment by blender** [comment]
Implemented in #108 

please try the binary at https://github.com/blender/Rome/releases/tag/v0.13.1.34

**Comment by blender** [comment]
@c0diq Do you have any feedback on the build?

**Comment by c0diq** [comment]
Works great. Thank you!

**Comment by c0diq** [comment]
Unrelated but is it possible you use a semantic version with only 3 digits? Using 4 digits such as 0.13.1.34 breaks semantic versioning parsing tools that expect only 3. Typically the 3rd one is the build number (your 34).

**Comment by blender** [comment]
@c0diq i'll close this issue. Please open another one for the version number.
