### ISSUE TITLE
Symbols are not uploaded

### ISSUE THREAD

**Issue by erichoracek** [blender/Rome#11]
The following carthage command:

```
carthage build ReactiveCocoa --platform ios
```

produces the outputs:

```
Carthage/Build/iOS/ReactiveCocoa.framework
Carthage/Build/iOS/ReactiveCocoa.framework.dSYM
```

However, invoking:

```
rome upload ReactiveCocoa
```

Only uploads the framework, not the `dSYM`.

It would seem that rome should cache not just `.framework` files matching the framework name, but rather any files matching the prefix of the framework name.

**Comment by blender** [comment]
How do you see this working in case either the framework is missing or the  dSYM is missing ?

Should `rome (upload | download) ReactiveCocoa` fail if either is missing?
How would this work with `rome list ([--missing] | [--present])`? When should rome report a cache miss?

**Comment by erichoracek** [comment]
Since there is not a guarantee that a dSYM will be available for a prebuilt framework in zipped GitHub releases that Carthage consumes, I don't think Rome should require symbols to be available either. It seems like Rome should just opportunistically upload all `Carthage/Build` products prefixed by the framework name, and do the equivalent during downloads.

With respect to the above scenario, if `ReactiveCocoa.dSYM` was present in the `Carthage/Build` directory, this would result in it being included in `rome (upload|download) ReactiveCocoa`, but if it was not present, it would be omitted entirely with no failures.

Since the framework is the critical artifact (dSYMs are just a nice-to-have), you would imagine that `rome list` would still function as it does currently.

Finally, I don't think this should be a command line switch to follow the precedence of Carthage, which does this automatically without user intervention.

Hope that helps clear things up. Thanks!

**Comment by blender** [comment]
Hi, this will be the next feature once the Romefile has moved to the INI format. 

- For contributors: `dSYM` are found in the same directory as the frameworks and must be zipped as well.

**Comment by blender** [comment]
Available in pre-release https://github.com/blender/Rome/releases/tag/v0.5.0.6

**Comment by blender** [comment]
Available from https://github.com/blender/Rome/releases/tag/v0.5.0.7 onwards
