### ISSUE TITLE
Include binary-only dependencies in Rome cache

### ISSUE THREAD

**Issue by chrispcampbell** [blender/Rome#110]
#### Enhancement Suggestion

Make Rome take `binary` dependencies into account from `Cartfile`.

**Steps which explain the enhancement**

1. Check for `binary` dependencies in `Cartfile` / `Cartfile.resolved`.
2. Take those into account so that they are included in the local Rome cache (so that the network download can be avoided if already cached locally).

**Current and suggested behavior**

It appears that currently Rome does not take binary-only Carthage dependencies into account.  For projects like ours that depend on large, externally-hosted binaries, this means we have to add an extra step that does `carthage bootstrap <binarydeps>` to ensure those dependencies are available in the `Carthage/Binaries` directory, which means always making a network request.  (Even on a fast connection this might add 10-30 seconds to a build, whereas if the local cache could be used it would be < 1 second.)

**Why would the enhancement be useful to most users**

For any users relying on binary-only dependencies, it would no longer be necessary to add special workarounds, and builds would be faster by taking advantage of locally cached binaries instead of making network requests.

**Rome version:** 0.13.0.33
**OS and version:** macOS 10.12.6

**Comment by blender** [comment]
Hi, thanks for opening an issue and taking time to suggest an improvement.

I understand the issue and would like to find a solution.
I belive it's doable and I suggest the following.

Consider:

```
https://raw.githubusercontent.com/Building42/Specs/master/Carthage/Answers.json "1.3.6"
```
- rome will strip `.json` from the end of a "binary" dependency. "git" or "github" dependencies will not be stripped. 
- __Without__ a `[RepositoryMap]` entry this will make rome  look for `Answers.framework` 
- __Whit__ a `[RepositoryMap]` like Answers  = AnswersiOS Rome will look for whatever you tell it to.

Sounds good?

**Comment by blender** [comment]
This was actually easy to implement. No idea why I didn't do it in the first place.

Please try pre-release https://github.com/blender/Rome/releases/tag/v0.13.1.35

Let me know if it works as expected and I will make a full release. I would also be very grateful if you could try the `--no-ignore` flag introduced with #107

**Comment by chrispcampbell** [comment]
Thank you for the fast turnaround, this all looks great!

I'm happy to report that I tried out v0.13.1.35 and it works as advertised for our binary dependencies.

I also added an `[IgnoreMap]` just for testing purposes and tried it out with the new `--no-ignore` flag and that also seems to be working correctly.

**Comment by blender** [comment]
Implemented.
