### ISSUE TITLE
Support for Bintray

### ISSUE THREAD

**Issue by rob-nash** [blender/Rome#120]
Hi,

This solution is pretty cool. Setting up Amazon S3 looks scary though. Something like bintray might be cool?

https://bintray.com/

**Comment by blender** [comment]
@rob-nash I took a look at Bintray and I have few questions I could not find an answer to.

- Bintray's Authentication requires Username/APIKey. Is there a standard location to store these? like `~/.bintray/credentials` 
- Bintray's repos are namespaced with `:subject`.
```
GET https://dl.bintray.com/:subject/:repo/:file_path
GET https://:subject.bintray.com/:repo/:file_path // Enterprise only
```
 I guess this value should be configurable rather than just take the username of the current user?

I don't have access to the enterprise version so I can't implement anything that requires that version.

**Comment by rob-nash** [comment]
Hi there.

I am new to Bintray myself. I setup an open source account yesterday and uploaded some binaries via their API. Seems pretty good.

Open source accounts are free. I think I need to accept a EULA before I attempt my first download of one of these binaries. I'll get back to you on that.

<img width="1018" alt="screen shot 2018-05-17 at 08 30 46" src="https://user-images.githubusercontent.com/14126999/40162820-fa266372-59ac-11e8-9420-44a70e94d17f.png">

Facebook v0.3.0 is 18Mb so my Carthage bootstrap is pretty slow! This is a snapshot of an API call I built with [postman](https://www.getpostman.com).

<img width="750" alt="screen shot 2018-05-17 at 08 29 44" src="https://user-images.githubusercontent.com/14126999/40162857-170fc834-59ad-11e8-8368-fbbd2a9dcb3b.png">

```
baseURL = https://api.bintray.com
```

<img width="774" alt="screen shot 2018-05-17 at 08 31 14" src="https://user-images.githubusercontent.com/14126999/40162882-2862990e-59ad-11e8-80fc-2654d5753bf7.png">

Maybe just support open source accounts, for now?

**Comment by rob-nash** [comment]
If I attempt to download one of these binaries myself with

```
https://dl.bintray.com/rob-nash/BinaryDump/iOS/dequable.zip
```

I don't need to accept a EULA.

The repo is public so I think someone attempting to download this without a Binary account, might get an error code and must accept a EULA, beforehand.

It might be easier to mention in README

1. create a free account
2. accept EULA
3. use Rome

**Comment by blender** [comment]
Hi,

The cache structure that Rome uses is not quite what you have there, so I'll explain to understand if this is fine also for Bintray.

`.dSYM`, `.framework`, `.version`, `.bsymbolmap` are handled separately. They are zipped separately and stored at separate locations. Locations where artifacts are stored follow some conventions derived from the Cartfile.resolved.

See https://github.com/blender/Rome#cache-structure

For example, dequable would be stored at:

```
https://dl.bintray.com/rob-nash/Dequable/iOS/Dequable.framework.1.3.0.zip
https://dl.bintray.com/rob-nash/Dequable/iOS/Dequable.framework.dSYM.1.3.0.zip
https://dl.bintray.com/rob-nash/Dequable/Dequable.version.1.3.0.zip
```

If I break this down in Bintray terms this would be
```
https://dl.bintray.com/:subject/:repo    /:file_path
https://dl.bintray.com/rob-nash/Dequable/iOS/Dequable.framework.1.3.0.zip
```

I'm trying to understand if this is legal with the API or not.

**Comment by rob-nash** [comment]
The 'file_path' parameter can specify any path. So for instance, I currently have one file located under /iOS

<img width="774" alt="screen shot 2018-05-17 at 08 31 14" src="https://user-images.githubusercontent.com/14126999/40166116-ae0b4576-59b5-11e8-8d8f-fbb0a7081242.png">

But I guess there is no harm is building any file structure you want, inside the bintray repo.

Could we not just create one file named `Dequable.zip` which contains all 3?

<img width="348" alt="screen shot 2018-05-17 at 09 37 25" src="https://user-images.githubusercontent.com/14126999/40166283-12c20338-59b6-11e8-9318-7fc6f01f7e93.png">

**Comment by blender** [comment]
Cool! I'll play some more around and see that I can do.

The reasons for not having one zip are:
1. Have the version file accessible ahead of downloading the binary (the version file is like a manifest)
1. Allow upload/download of resources separately 
1. Don't have to replace the whole zip if one file is missing

**Comment by blender** [comment]
@rob-nash When you uploaded your binaries, what did you use as `version` in the api?

In my idea this would be the version state in the `Cartfile.resolved` of the library you're trying to upload.

What is the point of `version` ? I don't see how it's used in the download API.

**Comment by rob-nash** [comment]
**Upload**

Set a header in your request

```
X-Bintray-Version
```

**Download**

In the above example `Dequable` is a package.

[Get package](https://bintray.com/docs/api/#_get_package) will give you the available `versions`.

[Get Version Files](https://bintray.com/docs/api/#_get_version_files) returns the files found for that version.

**Comment by blender** [comment]
So what version is at https://dl.bintray.com/rob-nash/BinaryDump/iOS/dequable.zip ? Where is the package information here?

I find this service very confusing in general, or at least confusing to use given how Rome works.

Rome has to go from a `Cartfile.resolved` like this

```
github "Alamofire/Alamofire" "4.7.2"
git "ssh://git@stash.someserver.com:7999/iossdk/ios-rest.git" "v7.1.0"
binary "https://raw.githubusercontent.com/Building42/Specs/master/Carthage/Answers.json" "1.3.6" 
```
to upload/download locations in Bintray

The upload API is: 

`PUT /content/:subject/:repo/:package/:version/:file_path`

`:subject` will be something configurable but `:repo` and `:package` have to be derivable from the Cartfile.resolved

How would Rome derive `:repo` and `:package` from the above Cartfile.resolved for all 3 cases?

Note that `ios-rest` is not the final name of the framework binary, this is why there is a https://github.com/blender/Rome#repositorymap section

**Comment by rob-nash** [comment]
You have a lot of work and Bintray looks like quite a bit of effort. Let me see if I can build a small wrapper for Bintray, deployable as a cross-platform executable.

It might take me a while, so you might want to close this ticket for now.

If I am successful, I will re-open this ticket, so you can take a look at my work and assess if it is suitable for Rome.

What you think?

**Comment by rob-nash** [comment]
Looks like there is already a wrapper 👍 

Phew!

https://www.npmjs.com/package/bintray

**Comment by blender** [comment]
If I understand correctly you're idea is to have 1 `:repo` where each  dependency in the Cartfile.resolved is a package.

So, in practice, given the following Cartfile.resolved
```
github "Alamofire/Alamofire" "4.7.2"
git "ssh://git@stash.someserver.com:7999/iossdk/ios-rest.git" "v7.1.0"
binary "https://raw.githubusercontent.com/Building42/Specs/master/Carthage/Answers.json" "1.3.6"
```

where ios-rest.git resolves to 2 targets Rest.framework and `Helper.framework`


It would translate to:

 ```
PUT /content/:subject   /:repo    /:package  /:version/:file_path
PUT /content/rob-nash/BinaryDump/Alamofire/   4.7.2   /Alamofire/iOS/Alamofire.framework.1.3.0.zip
PUT /content/rob-nash/BinaryDump/Alamofire/   4.7.2   /Alamofire/iOS/Alamofire.framework.1.3.0.dSYM.zip
PUT /content/rob-nash/BinaryDump/Alamofire/   4.7.2   /Alamofire/Alamofire.version.1.3.0.zip

PUT /content/:subject   /:repo  /:package  /:version /:file_path
PUT /content/rob-nash/BinaryDump/ios-rest/   7.1.0   /ios-rest/iOS/Rest.framework.7.1.0.zip
PUT /content/rob-nash/BinaryDump/ios-rest/   7.1.0   /ios-rest/iOS/Rest.framework.7.1.0.dSYM.zip
PUT /content/rob-nash/BinaryDump/ios-rest/   7.1.0   /ios-rest/ios-rest.version.1.3.0.zip
PUT /content/rob-nash/BinaryDump/ios-rest/   7.1.0   /ios-rest/iOS/Helper.framework.7.1.0.zip
PUT /content/rob-nash/BinaryDump/ios-rest/   7.1.0   /ios-rest/iOS/Helper.framework.7.1.0.dSYM.zip

PUT /content/:subject   /:repo  /:package  /:version   /:file_path
PUT /content/rob-nash/BinaryDump/Answers/   1.3.6      /Answers/iOS/Alamofire.framework.1.3.0.zip
PUT /content/rob-nash/BinaryDump/Answers/   1.3.6      /Answers/iOS/Alamofire.framework.1.3.0.dSYM.zip
PUT /content/rob-nash/BinaryDump/Answers/   1.3.6      /Answers/Answers.version.1.3.0.zip
```
 

So, puts are solved.

How about Gets?

Should the flow be:
- get package
- get version
- get final URL ?

**Comment by rob-nash** [comment]
Hi. Sorry for delay.

Yes, I believe it should be as you say. Perform get 1, perform get 2, then build URL.

**Comment by blender** [comment]
@rob-nash Thanks to @BalestraPatrick  you can now use [whatever backend you want](https://github.com/blender/Rome/#custom-engine)

**Comment by blender** [comment]
You can try the pre-release at: https://github.com/blender/Rome/releases/tag/v0.22.0.59
