### ISSUE TITLE
Allow un-authententicated download access to S3 repository

### ISSUE THREAD

**Issue by LesterTheTester** [blender/Rome#126]
## Enhancement Suggestion 

Allow unauthenticated access to S3 for downloading dependencies

**Why would the enhancement be useful to most users**

An administrator could setup an S3 bucket that's read-accessible to the public, or under certain ACL conditions (IP, VPC, etc) that do not require AWS credentials.  This would allow end users to consume dependencies without needing AWS credentials.  At some organizations, AWS credentials are not handed out to everyone (ie, only infrastructure developers). 

I'd suggest putting this behind a commandline flag, like --no-creds

**Comment by blender** [comment]
@LesterTheTester seems like a good idea. Do you want to give it a shot?

**Comment by blender** [comment]
@LesterTheTester I think it's enough to launch rome like so:

`AWS_ACCESS_KEY_ID="" AWS_SECRET_ACCESS_KEY="" rome download`

**Comment by samritchie** [comment]
@blender I might have a look at this one. Are you thinking http-conduit and using the command line flag as proposed?

**Comment by blender** [comment]
@samritchie 

If credentials are not discovered when a bucket is defined then an unauthenticated request should be made.

The CLI flag is needed to override the behavior regular behavior when credentials are there. I suggest the flag to be `--no-auth`

http-conduit to /tmp/some-zip then move to the appropriate location and unpack.

**Comment by blender** [comment]
@LesterTheTester  Thanks to @BalestraPatrick  you can now use [whatever backend you want](https://github.com/blender/Rome/#custom-engine), including implementing your own S3 script. https://github.com/blender/Rome/pull/185

**Comment by blender** [comment]
You can try the pre-release at: https://github.com/blender/Rome/releases/tag/v0.22.0.59
