### ISSUE TITLE
Not downloading existing bcsymbolmap files

### ISSUE THREAD

**Issue by Marus** [blender/Rome#131]
## Bug Report 

When attempting to use Rome currently with Carthage for an iOS project the bcsymbolmap files that are presented, and uploaded, do not get downloaded.

**Steps which explain the enhancement or reproduce the bug**

1. Create a Cartfile that has one an iOS dependencies. In my testing I used:
    `github "Alamofire/Alamofire" ~> 4.7`
2. Build the iOS libraries with Carthage (e.g. `carthage update Alamofire`).
3. After updating I have 4 files in my Carthage/Build/iOS folder:
    * Alamofire.framework
    * Alamofire.framework.dSYM
    * two bcsymbolmap files - these correspond to the UUIDs for the armv7 and arm64 UUIDs of the framework
4. Upload the build using `rome upload Alamofire --platform ios`, should upload the four files and the version info - this will successfully be uploaded the the S3 bucket configured.
5. (either on another machine, or after deleting Carthage/Build) Attempt to run `rome download Alamofire --platform ios`
Should get output similar to the following https://pastebin.com/qhy9c5cs
The output appears to download the framework, the framework.dSYM, the two bcsymbolmap files that were uploaded successfully, and the .Alamofire.version file, and to have errors for two additional bcsymbolmap files (these correspond to the i386 and x86_64 versions that were not generated by carthage and thus not uploaded) - yet the Carthage directory structure only has the `Carthage/Build/.Alamofire.version`, `Carthage/Build/ioS/Alamofire.framework`, and `Carthage/Build/iOS/Alamofire.framework.dSYM` files with no bcsymbolmap files.

**Current behavior**

Not downloading any of the bcsymbolmap files - even those that were uploaded successfully

**Suggested behavior**

Download the existing bcsymbolmap files

**Why would the enhancement be useful to most users**

Allow the bcsymbolmap files to be restored so that bitcode enable builds can be properly built.

**Rome version:** 

0.15.0.43 - Romam uno die non fuisse conditam.

**OS and version:** 

    OS: macOS 10.13.5
    Carthage: 0.30.1

**Comment by blender** [comment]
Thanks, I will look into it.

**Comment by blender** [comment]
Please try: https://github.com/blender/Rome/releases/tag/v0.16.0.45 issue should be fixed.

Can I add your company to https://github.com/blender/Rome#who-uses-rome ?

**Comment by Marus** [comment]
That seems to fix the issue - thanks.

Not using it within the company I work for currently - just been trying things out on some of my own projects. Although in the future I'd like to see us move away from CocoaPods to something like Carthage + Rome (although I still think the name is an odd choice; Rome was the enemy of Carthage, not a helper ;)). If we do adopt it maybe then.

**Comment by blender** [comment]
@Marus I'll make a full release this week with the fix included. This will happen as soon as I finish implementing support for carthage 0.30.1 Static Frameworks

**Comment by Marus** [comment]
Thanks - I'll use this release for the time being for my experiments. Looking forward to the static frameworks release as well - as I plan to start experimenting with that soon.

**Comment by Thiryn** [comment]
I would add that with 0.15.0.43 a download with local cache generates errors with `bcsymbolmap` files : 
`Error: could not find Alamofire.85164539-C664-3315-8D1F-F63F67662D6C.bcsymbolmap in local cache at : /Users/djolivald/Library/Caches/Rome/Alamofire/iOS/85164539-C664-3315-8D1F-F63F67662D6C.bcsymbolmap-4.7.2.zip`
or when downloading for first time :
`Error: no such file Carthage/Build/iOS/08FF025B-F161-3B9B-83B1-28197ED791DC.bcsymbolmap` 
Even though the `Carthage/Build/iOS/08FF025B-F161-3B9B-83B1-28197ED791DC.bcsymbolmap` file is created.

**Comment by blender** [comment]
@Thiryn  do you see this happen with https://github.com/blender/Rome/releases/tag/v0.16.0.45 as well?

**Comment by blender** [comment]
🤦‍♂️  `08FF025B-F161-3B9B-83B1-28197ED791DC`

**Comment by blender** [comment]
Seems to work fine for me. Some of the errors you see are because there is no bcsymbolmap for some architectures (`i386`, `x86_64`)

**Comment by Thiryn** [comment]
Sorry, I just took the time to build it for the version you asked, I still have exactly the same messages.
If I simply run it with one dependency:
```
 $> carthage bootstrap --platform iOS --no-use-binaries --cache-builds             
*** Checking out Quick at "v1.3.0"
*** No cache found for Quick, building with all downstream dependencies
*** xcodebuild output can be found in /var/folders/f9/33ntg5xj38n_5xrdj7rc7bqh0000gq/T/carthage-xcodebuild.dUzKuw.log
*** Building scheme "Quick-iOS" in Quick.xcworkspace
 $>  rome upload --platform iOS                                                                                             
Copied Quick.framework to: /path/to/Library/Caches/Rome/Quick/iOS/Quick.framework-v1.3.0.zip
Copied Quick.dSYM to: /path/to/Library/Caches/Rome/Quick/iOS/Quick.framework.dSYM-v1.3.0.zip
Copied .Quick.version to: /path/to/Library/Caches/Rome/Quick/.Quick.version-v1.3.0
 $> rm -rf Carthage/                                                                                                     
 $> rome download --platform iOS | grep -i ERROR
Error: could not find Quick.BC3C622D-8741-35E3-9710-C5D77C03B5BC.bcsymbolmap in local cache at : /path/to/Library/Caches/Rome/Quick/iOS/BC3C622D-8741-35E3-9710-C5D77C03B5BC.bcsymbolmap-v1.3.0.zip
Error: could not find Quick.8F501DFD-46B9-30B0-A87D-0EBD1F61F7E9.bcsymbolmap in local cache at : /path/to/Library/Caches/Rome/Quick/iOS/8F501DFD-46B9-30B0-A87D-0EBD1F61F7E9.bcsymbolmap-v1.3.0.zip
Error: could not find Quick.1AC11F55-86CB-31C9-A44B-C6E94122FA39.bcsymbolmap in local cache at : /path/to/Library/Caches/Rome/Quick/iOS/1AC11F55-86CB-31C9-A44B-C6E94122FA39.bcsymbolmap-v1.3.0.zip
Error: could not find Quick.3AF41422-72DA-3460-B567-26B3067002C8.bcsymbolmap in local cache at : /path/to/Library/Caches/Rome/Quick/iOS/3AF41422-72DA-3460-B567-26B3067002C8.bcsymbolmap-v1.3.0.zip
```

**Comment by blender** [comment]
Thanks! 

I'll try with Quick. I see that symbolmaps are not uploaded to begin with. Maybe there aren't any.

**Comment by blender** [comment]
@Thiryn Quick doens't produce bcsymbolmaps.

Rome says "Error" but what it means is just "Cache miss"

**Comment by Thiryn** [comment]
Well, if quick does not produce bcsymbolmaps, it means none are uploaded, then why is Rome trying to get them on downloads ?

**Comment by blender** [comment]
Because there is no way to know it dosn't produce bcsymbolmaps

If you can think of way I would be happy to discuss it

**Comment by Thiryn** [comment]
Owh! I see, then maybe indicating a cache miss instead of an error, as there is no error from Rome, just an non-existing file. And maybe even showing it only on verbose, I don't know if the cache-miss information has value without verbose.

**Comment by blender** [comment]
Point taken. Thanks for the input!

**Comment by Thiryn** [comment]
Happy to help! :p

**Comment by LSJFR** [comment]
Hi,

I have the same issue with the latest version

`rome --version`
`0.18.0.51 - Romam uno die non fuisse conditam.`


I type this command :
`
rome upload DZNEmptyDataSet --platform ios
`

and i have this :
`
Uploaded DZNEmptyDataSet to: DZNEmptyDataSet/iOS/DZNEmptyDataSet.framework-v1.8.1.zip
Uploaded DZNEmptyDataSet.dSYM to: DZNEmptyDataSet/iOS/DZNEmptyDataSet.framework.dSYM-v1.8.1.zip
Uploaded DZNEmptyDataSet.E7A3AB6E-7DC0-38C4-9312-E96A1111C000.bcsymbolmap to: DZNEmptyDataSet/iOS/E7A3AB6E-7DC0-38C4-9312-E96A1111C000.bcsymbolmap-v1.8.1.zip
Uploaded DZNEmptyDataSet.53AB40B0-4E1D-3D43-9860-1DC34BC861EB.bcsymbolmap to: DZNEmptyDataSet/iOS/53AB40B0-4E1D-3D43-9860-1DC34BC861EB.bcsymbolmap-v1.8.1.zip
Uploaded .DZNEmptyDataSet.version to: DZNEmptyDataSet/.DZNEmptyDataSet.version-v1.8.1
`

When i download :

`rome download DZNEmptyDataSet --platform ios`

i have this :

`Downloaded DZNEmptyDataSet from: DZNEmptyDataSet/iOS/DZNEmptyDataSet.framework-v1.8.1.zip
Downloaded DZNEmptyDataSet.dSYM from: DZNEmptyDataSet/iOS/DZNEmptyDataSet.framework.dSYM-v1.8.1.zip
Downloaded DZNEmptyDataSet.E7A3AB6E-7DC0-38C4-9312-E96A1111C000.bcsymbolmap from: DZNEmptyDataSet/iOS/E7A3AB6E-7DC0-38C4-9312-E96A1111C000.bcsymbolmap-v1.8.1.zip
Downloaded DZNEmptyDataSet.53AB40B0-4E1D-3D43-9860-1DC34BC861EB.bcsymbolmap from: DZNEmptyDataSet/iOS/53AB40B0-4E1D-3D43-9860-1DC34BC861EB.bcsymbolmap-v1.8.1.zip
Error: could not download DZNEmptyDataSet.4854F5B9-405A-3B2D-960F-6EFB6FC35862.bcsymbolmap : ServiceError (ServiceError' {_serviceAbbrev = Abbrev "S3", _serviceStatus = Status {statusCode = 404, statusMessage = "Not Found"}, _serviceHeaders = [("Accept-Ranges","bytes"),("Content-Security-Policy","block-all-mixed-content"),("Content-Type","application/xml"),("Server","Minio/RELEASE.2018-11-15T01-26-07Z (linux; amd64)"),("Vary","Origin"),("X-Amz-Request-Id","15679369291A5A42"),("X-Xss-Protection","1; mode=block"),("Date","Fri, 16 Nov 2018 10:17:57 GMT"),("Transfer-Encoding","chunked")], _serviceCode = ErrorCode "NoSuchKey", _serviceMessage = Just (ErrorMessage "The specified key does not exist."), _serviceRequestId = Just (RequestId "15679369291A5A42")})
Error: could not download DZNEmptyDataSet.12CA7858-33DF-3D9D-B791-509C7DF04998.bcsymbolmap : ServiceError (ServiceError' {_serviceAbbrev = Abbrev "S3", _serviceStatus = Status {statusCode = 404, statusMessage = "Not Found"}, _serviceHeaders = [("Accept-Ranges","bytes"),("Content-Security-Policy","block-all-mixed-content"),("Content-Type","application/xml"),("Server","Minio/RELEASE.2018-11-15T01-26-07Z (linux; amd64)"),("Vary","Origin"),("X-Amz-Request-Id","1567936929312B99"),("X-Xss-Protection","1; mode=block"),("Date","Fri, 16 Nov 2018 10:17:57 GMT"),("Transfer-Encoding","chunked")], _serviceCode = ErrorCode "NoSuchKey", _serviceMessage = Just (ErrorMessage "The specified key does not exist."), _serviceRequestId = Just (RequestId "1567936929312B99")})
Downloaded .DZNEmptyDataSet.version from: DZNEmptyDataSet/.DZNEmptyDataSet.version-v1.8.1
Copied .DZNEmptyDataSet.version to: Carthage/Build/.DZNEmptyDataSet.version`

verbose version :

`11:18:25 2018-11-16 - Started downloading DZNEmptyDataSet from: DZNEmptyDataSet/iOS/DZNEmptyDataSet.framework-v1.8.1.zip
11:18:25 2018-11-16 - Downloaded 0.29 MB of 0.29 MB for DZNEmptyDataSet
11:18:25 2018-11-16 - Downloaded DZNEmptyDataSet from: DZNEmptyDataSet/iOS/DZNEmptyDataSet.framework-v1.8.1.zip
11:18:25 2018-11-16 - Deleted: Carthage/Build/iOS/DZNEmptyDataSet.framework
11:18:25 2018-11-16 - Staring to unzip DZNEmptyDataSet.framework-v1.8.1.zip
11:18:25 2018-11-16 - Unzipped DZNEmptyDataSet from: DZNEmptyDataSet.framework-v1.8.1.zip
11:18:25 2018-11-16 - Started downloading DZNEmptyDataSet.dSYM from: DZNEmptyDataSet/iOS/DZNEmptyDataSet.framework.dSYM-v1.8.1.zip
11:18:25 2018-11-16 - Downloaded 1.00 MB of 1.43 MB for DZNEmptyDataSet.dSYM
11:18:25 2018-11-16 - Downloaded 1.43 MB of 1.43 MB for DZNEmptyDataSet.dSYM
11:18:25 2018-11-16 - Downloaded DZNEmptyDataSet.dSYM from: DZNEmptyDataSet/iOS/DZNEmptyDataSet.framework.dSYM-v1.8.1.zip
11:18:25 2018-11-16 - Deleted: Carthage/Build/iOS/DZNEmptyDataSet.framework.dSYM
11:18:25 2018-11-16 - Staring to unzip DZNEmptyDataSet.framework.dSYM-v1.8.1.zip
11:18:25 2018-11-16 - Unzipped DZNEmptyDataSet from: DZNEmptyDataSet.framework.dSYM-v1.8.1.zip
11:18:25 2018-11-16 - Started downloading DZNEmptyDataSet.4854F5B9-405A-3B2D-960F-6EFB6FC35862.bcsymbolmap from: DZNEmptyDataSet/iOS/4854F5B9-405A-3B2D-960F-6EFB6FC35862.bcsymbolmap-v1.8.1.zip
11:18:25 2018-11-16 - Started downloading DZNEmptyDataSet.12CA7858-33DF-3D9D-B791-509C7DF04998.bcsymbolmap from: DZNEmptyDataSet/iOS/12CA7858-33DF-3D9D-B791-509C7DF04998.bcsymbolmap-v1.8.1.zip
11:18:25 2018-11-16 - Started downloading DZNEmptyDataSet.E7A3AB6E-7DC0-38C4-9312-E96A1111C000.bcsymbolmap from: DZNEmptyDataSet/iOS/E7A3AB6E-7DC0-38C4-9312-E96A1111C000.bcsymbolmap-v1.8.1.zip
11:18:25 2018-11-16 - Downloaded 0.00 MB of 0.00 MB for DZNEmptyDataSet.E7A3AB6E-7DC0-38C4-9312-E96A1111C000.bcsymbolmap
11:18:25 2018-11-16 - Downloaded DZNEmptyDataSet.E7A3AB6E-7DC0-38C4-9312-E96A1111C000.bcsymbolmap from: DZNEmptyDataSet/iOS/E7A3AB6E-7DC0-38C4-9312-E96A1111C000.bcsymbolmap-v1.8.1.zip
11:18:25 2018-11-16 - Deleted: Carthage/Build/iOS/E7A3AB6E-7DC0-38C4-9312-E96A1111C000.bcsymbolmap
11:18:25 2018-11-16 - Staring to unzip E7A3AB6E-7DC0-38C4-9312-E96A1111C000.bcsymbolmap-v1.8.1.zip
11:18:25 2018-11-16 - Unzipped DZNEmptyDataSet.E7A3AB6E-7DC0-38C4-9312-E96A1111C000.bcsymbolmap from: E7A3AB6E-7DC0-38C4-9312-E96A1111C000.bcsymbolmap-v1.8.1.zip
11:18:25 2018-11-16 - Started downloading DZNEmptyDataSet.53AB40B0-4E1D-3D43-9860-1DC34BC861EB.bcsymbolmap from: DZNEmptyDataSet/iOS/53AB40B0-4E1D-3D43-9860-1DC34BC861EB.bcsymbolmap-v1.8.1.zip
11:18:25 2018-11-16 - Downloaded 0.00 MB of 0.00 MB for DZNEmptyDataSet.53AB40B0-4E1D-3D43-9860-1DC34BC861EB.bcsymbolmap
11:18:25 2018-11-16 - Downloaded DZNEmptyDataSet.53AB40B0-4E1D-3D43-9860-1DC34BC861EB.bcsymbolmap from: DZNEmptyDataSet/iOS/53AB40B0-4E1D-3D43-9860-1DC34BC861EB.bcsymbolmap-v1.8.1.zip
11:18:25 2018-11-16 - Deleted: Carthage/Build/iOS/53AB40B0-4E1D-3D43-9860-1DC34BC861EB.bcsymbolmap
11:18:25 2018-11-16 - Staring to unzip 53AB40B0-4E1D-3D43-9860-1DC34BC861EB.bcsymbolmap-v1.8.1.zip
11:18:25 2018-11-16 - Unzipped DZNEmptyDataSet.53AB40B0-4E1D-3D43-9860-1DC34BC861EB.bcsymbolmap from: 53AB40B0-4E1D-3D43-9860-1DC34BC861EB.bcsymbolmap-v1.8.1.zip
11:18:25 2018-11-16 - Error: could not download DZNEmptyDataSet.4854F5B9-405A-3B2D-960F-6EFB6FC35862.bcsymbolmap : ServiceError (ServiceError' {_serviceAbbrev = Abbrev "S3", _serviceStatus = Status {statusCode = 404, statusMessage = "Not Found"}, _serviceHeaders = [("Accept-Ranges","bytes"),("Content-Security-Policy","block-all-mixed-content"),("Content-Type","application/xml"),("Server","Minio/RELEASE.2018-11-15T01-26-07Z (linux; amd64)"),("Vary","Origin"),("X-Amz-Request-Id","1567936FA7BF7984"),("X-Xss-Protection","1; mode=block"),("Date","Fri, 16 Nov 2018 10:18:25 GMT"),("Transfer-Encoding","chunked")], _serviceCode = ErrorCode "NoSuchKey", _serviceMessage = Just (ErrorMessage "The specified key does not exist."), _serviceRequestId = Just (RequestId "1567936FA7BF7984")})
11:18:25 2018-11-16 - Error: could not download DZNEmptyDataSet.12CA7858-33DF-3D9D-B791-509C7DF04998.bcsymbolmap : ServiceError (ServiceError' {_serviceAbbrev = Abbrev "S3", _serviceStatus = Status {statusCode = 404, statusMessage = "Not Found"}, _serviceHeaders = [("Accept-Ranges","bytes"),("Content-Security-Policy","block-all-mixed-content"),("Content-Type","application/xml"),("Server","Minio/RELEASE.2018-11-15T01-26-07Z (linux; amd64)"),("Vary","Origin"),("X-Amz-Request-Id","1567936FA7D42E6D"),("X-Xss-Protection","1; mode=block"),("Date","Fri, 16 Nov 2018 10:18:25 GMT"),("Transfer-Encoding","chunked")], _serviceCode = ErrorCode "NoSuchKey", _serviceMessage = Just (ErrorMessage "The specified key does not exist."), _serviceRequestId = Just (RequestId "1567936FA7D42E6D")})
11:18:25 2018-11-16 - Started downloading .DZNEmptyDataSet.version from: DZNEmptyDataSet/.DZNEmptyDataSet.version-v1.8.1
11:18:25 2018-11-16 - Downloaded 0.00 MB of 0.00 MB for .DZNEmptyDataSet.version
11:18:25 2018-11-16 - Downloaded .DZNEmptyDataSet.version from: DZNEmptyDataSet/.DZNEmptyDataSet.version-v1.8.1
11:18:25 2018-11-16 - Copied .DZNEmptyDataSet.version to: Carthage/Build/.DZNEmptyDataSet.version`


I'm using minio as S3 Server.

Any ideas ?

Thanks !

**Comment by blender** [comment]
Let me run the tests on master

**Comment by LSJFR** [comment]
hummm, ok.

Carthage build this files :

<img width="483" alt="capture d ecran 2018-11-16 a 14 07 53" src="https://user-images.githubusercontent.com/10814086/48623098-09ebe700-e9a9-11e8-99d0-7788da756c22.png">

When i upload with Rome, only 2 .bcsymbol files are uploaded.

Why the download action try to download 4 .bcsymbol files ?

Thanks !

**Comment by blender** [comment]
Because the .bcsymbolmaps are generate by Xcode only for the supported architectures specified in the your project. 

However, one can always obtain ids for all architectures from the `dSYM`. If you are curious how this is the bit: https://github.com/blender/Rome/blob/master/src/Xcode/DWARF.hs#L57-L73

**Comment by PatrickKaalund** [comment]
I also have an issue related to this. 

First build locally and upload to Rome. 
Second download from Rome contains errors like:

Error: could not download ZIPFoundation.1D89912F-74C5-3987-9BBF-03F955E168FD.bcsymbolmap : The specified key does not exist.
Error: could not download ZIPFoundation.F3D2BDEF-A362-3999-B243-CB8BE1FA09CB.bcsymbolmap : The specified key does not exist.

Investigating the .bcsymbolmaps after shows that they contains absolute paths to my user:
/Users/patrick/Documents/workspace/{app}/Carthage/Checkouts/ZIPFoundation/Sources/ZIPFoundation

Downloading on other machines, doesn't work as pointing to absolute path?

Downloading from my machine, gives the above errors?

**Comment by tmspzz** [comment]
@PatrickKaalund  take a minute to read the discussion. It's normal for a number of `.bcsymbolmap` to be missing.

Rome doesn't touch any path in the symbolmap

**Comment by PatrickKaalund** [comment]
Alright. 

Meaning it ins't a Rome problem with the absolute paths as well?

Did you work on a system to prevent throwing errors on specific libs?

**Comment by tmspzz** [comment]
The absolute paths contained is the symbolmap are from the machine that built the framework. Rome doesn't, and shouldn't, touch that.

Desymbolication will work just fine.

**Comment by timbo24** [comment]
Is there anyway to suppress missing .bcsymbolmap errors when downloading from the cache?

**Comment by tmspzz** [comment]
`rome ... grep -v "Error: *.*\.bcsymbolmap"`
