### ISSUE TITLE
Where is version 0.17.0.47?

### ISSUE THREAD

**Issue by joshfriend** [blender/Rome#142]
## Enhancement Suggestion / Bug Report 

There are multiple references in the README/wiki docs to versions after 0.17.x.x, but none actually exist.

**Steps which explain the enhancement or reproduce the bug**

1. Set up project as described in README with `Romefile` in yaml format
2. run `rome install`
3. Get this error: `Error while parsing Romefile: Could not find section: "Cache"`

**Rome version:** 

0.16.0.46 (installed from [tap](https://github.com/blender/homebrew-tap/blob/master/rome.rb))

this is the newest version available from any source (git tags/cocoapods/homebrew tap)

**OS and version:** 

macOS 10.13.6

**Comment by blender** [comment]
It's coming, there are no new features or differences between 0.16.0.46 and 0.17.x.x as of yet (unless you want to migrate the Romefile to `YAML` for some reason)

If you need the old docs there is a link to the wiki in the new docs. Here is the link anyways https://github.com/blender/Rome/wiki/Romefile-prior-0.17.x.x

**Comment by blender** [comment]
It's out https://github.com/blender/Rome/releases/tag/v0.17.0.48
