### ISSUE TITLE
Framework missing [help wanted]

### ISSUE THREAD

**Issue by Max0u** [blender/Rome#154]
Hi ! First, thanks for your awesome project.

Once I run :

```bash
rome upload
```

and then I run :

```bash
rome download
````

There is some missing framework. 

For exemple with Moya framework when I build with Carthage I got RxMoya but it seems that I only upload Moya.

Here is my Romefile :

```
cache: # required
  local: ~/Library/Caches/Rome
```

What did I do wrong ?

Thanks !

**Rome version:** 

    [0.17.2.50]

**OS and version:** 

    [Mac OS 10.14]

**Comment by blender** [comment]
@Max0u 

If your framework produces more the one target you need to add a `repositoryMap`.

In the `repositoryMay` you can specify what produces what. So for Moya:

```
repositoryMap: # optional
- Moya: 
  - name: Moya
  - name: RxMoya
  .....
```

**Comment by Max0u** [comment]
That's perfect ! And if I got framework from binary like that :

```
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json" ~> 5.8.0
```

Can I go with :

```
- FirebaseAnalyticsBinary: 
  - name: FirebaseAnalytics
```

Else that's awesome man !

**Comment by blender** [comment]
that should be correct

**Comment by blender** [comment]
@Max0u did that help? Please consider closing the issue if you don't have other questions ;)

**Comment by Max0u** [comment]
Yes it worked thanks again 👍
