### ISSUE TITLE
Parallel download/upload of binaries from S3.

### ISSUE THREAD

**Issue by sauravexodus** [blender/Rome#158]
## Enhancement Suggestion / Bug Report 

    Parallel uploads to S3 server using `--parallel` option

**Why would the enhancement be useful to most users**

    I sometimes experience slow downloading/uploading on my mac. This would enable the uploads and downloads to use the full bandwidth of the internet.

**Comment by blender** [comment]
I think it makes sense even without the flag.

I am not sure why I didn't consider it at the time. Listing is already parallelized. https://github.com/blender/Rome/blob/582cc2d6139baefa0d6da5bb5adc9f34cef63d91/src/Caches/S3/Probing.hs#L26

**Comment by sauravexodus** [comment]
Should I take this up?

**Comment by blender** [comment]
Sure. If you want to give it a try :)

**Comment by sauravexodus** [comment]
I get this weird error when I try to run `stack build`

<img width="1912" alt="screenshot 2018-11-25 at 11 40 21 pm" src="https://user-images.githubusercontent.com/7869346/48982661-8601cf80-f10b-11e8-9632-2bdc08fe9ac5.png">

**Comment by blender** [comment]
do you get it reliably?

**Comment by sauravexodus** [comment]
Yes. Even if I do a clean build.

**Comment by sauravexodus** [comment]
Yeah worked!! Thanks for the precise help :D

**Comment by blender** [comment]
Hey @sauravexodus were you able to make any progress?

**Comment by sauravexodus** [comment]
No, @blender I haven't gotten time yet.

**Comment by blender** [comment]
This is implemented in #174

**Comment by sauravexodus** [comment]
Awesome! 💃
