### ISSUE TITLE
currentMap ignored when using `rome upload <current_framework_repo_name>`

### ISSUE THREAD

**Issue by ScottBuchanan** [blender/Rome#160]
## Bug Report 

The `rome upload` command does not appear to use the `currentMap` when the current framework's repository name is passed in as a parameter.

**Reproduction Steps:**

1. have a `Romefile` with a `currentMap` entry that does not follow the "Organization/FrameworkName" convention. ie.
```
currentMap:
- better-dog-names:
  - name: DogFramework
```
2. run the rome upload command with current framework ie. `rome upload better-dog-names`

**Expected behavior:**

* The S3 bucket is populated with an artifact file structure something like:
```
better-dog-names
  → iOS
    → DogFramework.framework.1.0.0.zip
```

**Observed behavior:**

* The S3 bucket is populated with an artifact file structure something like:
```
DogFramework
  → iOS
    → DogFramework.framework.1.0.0.zip
```
* note the top level directory is created with the framework name instead of the repository name.

**Why would the enhancement be useful to most users**

* It would allow the `currentMap` feature to work in the intended way without forcing the unnecessary upload of the current project's dependencies (see additional information).
* Ultimately we want to be able to run `rome list --missing --no-skip-current` (which works as expected right now) and then pipe the results into our call to `rome upload`

**Rome version:**: 
* 0.18.0.51

**OS and version:**: 
* MacOS High Sierra 10.13.6

**Additional information:**

* This came about because we are uploading to rome with the `--no-skip-current` flag when there are only changes in the current repo (ie. we don't want to push all the dependencies of the current framework as well). 
    * Not specifying any specific frameworks with the `rome upload` command does properly create the folder structure on S3 but re-uploads all the dependencies of the framework as well (which IS the correct behavior for this command, but not ideal for our workflow).
* Thought we might be able to work around this by duplicating the `currentMap` entry into the `repositoryMap`, but there is no entry in the `Cartfile.resolved` so this didn't work.

**Comment by JesseScott** [comment]
agreed, this is an important functional change to have!

**Comment by blender** [comment]
Definitely a bug. Thanks for the detailed report, this should have not made it though my integration tests.

**Comment by blender** [comment]
Please try fix at https://github.com/blender/Rome/releases/tag/v0.18.1.52

**Comment by ScottBuchanan** [comment]
> Please try fix at https://github.com/blender/Rome/releases/tag/v0.18.1.52

yeah looks like its working for me now. Thanks for getting on that so quickly.

Sidenote: I saw you put in a fix for another issue that I'm hitting with carthage: https://github.com/Carthage/Carthage/issues/2634 

Any insights into when that might be released?

**Comment by blender** [comment]
@ScottBuchanan the PR that implements the fix on Carthage has already been merged https://github.com/Carthage/Carthage/pull/2636

You can install the version with the fix by running `brew install carthage --HEAD`

**Comment by blender** [comment]
@ScottBuchanan there is a bug in this version where current + ignore doesn't work properly and results in exactly there same weird cache path. I have corrected it and will issue another pre-release.

**Comment by blender** [comment]
Released here: https://github.com/blender/Rome/releases/tag/v0.18.1.53
