### ISSUE TITLE
Uploading incorrect version

### ISSUE THREAD

**Issue by c0diq** [blender/Rome#163]
## Enhancement Suggestion / Bug Report 

    When the Cartfile and the Cartfile.resolved versions differ, the wrong version is uploaded in the `.<framework>.version-v<version>` file.

**Steps which explain the enhancement or reproduce the bug**

1. 
Cartfile.private contains `github "Quick/Quick" ~> 1.3.1`
Carfile.resolved contains `github "Quick/Quick" "v1.3.4"`
2. Build with Carthage
3. Execute `rome upload --platform ios,macos  --cache-prefix Swift_4_2_1`
3. Check out file `.Quick.version-v1.3.4`

**Current behavior**

    The file incorrectly refers to version 1.3.1
```
{
  "commitish" : "v1.3.1",
  "Mac" : [
    {
      "name" : "Quick",
      "hash" : "ece6131aaeef3dfb9cf70b05f01504429e7b50cda1236f061ac2633ed49abaea"
    }
  ],
  "iOS" : [
    {
      "name" : "Quick",
      "hash" : "613ad8b42b617347f13922bb6f6fc287d596780e0f641125cf496b71c462a979"
    }
  ]
}
```

**Suggested behavior**

    File should have version v1.3.4

**Why would the enhancement be useful to most users**

When the file is fetched later from Rome, it has version 1.3.1 instead of 1.3.4 and links with the incorrect version. We identified the issue because we use https://github.com/Carthage/workflows/blob/master/carthage-verify which verifies that the version being linked is the one referenced in Cartfile.resolved.

**Rome version:** 

    0.18.0.51

**OS and version:** 

    10.13.6

**Comment by blender** [comment]
Hi, could it be that someone/something manually modified the Cartfile.resolved?

It would be great if you could reproduce this. I'll keep an eye out for it and verify with the workflow.

**Comment by c0diq** [comment]
@blender No. We don't touch the Cartfile.resolved manually. I am still unsure how I ended up in this state. We can close for now and reopen if I can reproduce. Thanks!
