### ISSUE TITLE
Rome fails to download with the latest Homebrew

### ISSUE THREAD

**Issue by sauravexodus** [blender/Rome#164]
## Bug Report 

Rome fails to download with the latest `brew` version

**Steps which explain the enhancement or reproduce the bug**

Try to run

`brew install blender/homebrew-tap/rome`

**Current behavior**

    Fails with an error
    Error: No available formula with the name "blender/tap/rome" 
    Please tap it and then try again: brew tap blender/tap
    Error: No similarly named formulae found.
    ==> Searching for similarly named formulae...

**Suggested behavior**

    Should install just fine

**OS and version:** 

    macOS Siera

**Comment by blender** [comment]
Hi, installation is working fine for me. What version of Homebrew do you have?

Alternatively try

```
brew tap blender/tap https://github.com/blender/homebrew-tap.git
brew install blender/homebrew-tap/rome
```

**Comment by blender** [comment]
I already updated the Readme, thanks for reporting https://github.com/blender/Rome#using-homebrew.

@sauravexodus can you confirm the new instructions are working for you?

**Comment by sauravexodus** [comment]
I was using 2.0.1 version of Homebrew. It works now

**Comment by sauravexodus** [comment]
Thanks for the quick revert
