### ISSUE TITLE
Rome does not recognize last entry in Cartfile.resolved if there's no new line at end

### ISSUE THREAD

**Issue by jbuckner** [blender/Rome#165]
## Enhancement Suggestion / Bug Report 

If there's no new line at the end of the last entry of `Cartfile.resolved`, Rome does not detect it as a dependency and doesn't upload or download it.

**Steps which explain the enhancement or reproduce the bug**

1. Remove any new line characters from the end of `Cartfile.resolved` so it ends at the last character of the last entry.
2. Run `rome upload` or `rome download`

**Current behavior**

`Rome` does not recognize the last entry in `Cartfile.resolved` and doesn't upload or download it. It doesn't throw any errors, just silently skips it.

**Suggested behavior**

`Rome` should recognize this last dependency

**Why would the enhancement be useful to most users**

This failure is silent and there's no indication that it has failed unless you look through the upload/download logs for the missing dependency.

**Rome version:** 

    `0.18.1.53`

**OS and version:** 

    Mac OS 10.14

**Comment by blender** [comment]
Thanks for reporting, I will investigate.

**Comment by blender** [comment]
Please try: https://github.com/blender/Rome/releases/tag/v0.18.2.53

This is a high risk change since I had to almost completely redo the parsing of the `Cartfile.resolved`

**Comment by jbuckner** [comment]
@blender Thank you for jumping on this so quickly! I tested `0.18.2.53` and it fixes the issue!

**Comment by blender** [comment]
@jbuckner released in https://github.com/blender/Rome/releases/tag/v0.19.0.55

I bumped the version number because of the new parser.

Are you using this project privately or for work? 
If you use it for work would you mind if I add your employer to the list of Rome users?
