### ISSUE TITLE
When downloading frameworks from cache lots of error messages are logged

### ISSUE THREAD

**Issue by leviathan** [blender/Rome#178]
## Question

When downloading cached frameworks, the console shows a lot of error messages.

**Steps which explain the enhancement or reproduce the bug**

1. Uploaded carthage dependency to AWS S3 bucket with:
```
$ carthage bootstrap --platform ios && rome upload --cache-prefix Swift_4_2_1
```
2. Tried to download the cached framework(s) from the AWS S3 cache.

**Current behavior**

When running
```
$ rome download --cache-prefix Swift_4_2_1 -v
```
.. the download works. 
But there are lots of console messages, which I don't understand. 
Are these indicators that something went wrong?

```
16:23:00 2019-04-04 - Unzipped CocoaLumberjack.7B8E1169-9CDC-3E4D-A202-46874C63FFED.bcsymbolmap from: 7B8E1169-9CDC-3E4D-A202-46874C63FFED.bcsymbolmap-3.5.2.zip
16:23:00 2019-04-04 - Error: could not find CocoaLumberjack.74186576-341F-3AFC-BB25-9FC4CAE91946.bcsymbolmap in local cache at : /Library/Caches/Rome/Swift_4_2_1/CocoaLumberjack/iOS/74186576-341F-3AFC-BB25-9FC4CAE91946.bcsymbolmap-3.5.2.zip
16:23:00 2019-04-04 - Error: could not find CocoaLumberjack.4F74522A-AF89-3DD8-A36C-10967E24AD77.bcsymbolmap in local cache at : /Library/Caches/Rome/Swift_4_2_1/CocoaLumberjack/iOS/4F74522A-AF89-3DD8-A36C-10967E24AD77.bcsymbolmap-3.5.2.zip
16:23:00 2019-04-04 - Started downloading CocoaLumberjack.74186576-341F-3AFC-BB25-9FC4CAE91946.bcsymbolmap from: Swift_4_2_1/CocoaLumberjack/iOS/74186576-341F-3AFC-BB25-9FC4CAE91946.bcsymbolmap-3.5.2.zip
16:23:00 2019-04-04 - Error: could not download CocoaLumberjack.74186576-341F-3AFC-BB25-9FC4CAE91946.bcsymbolmap : ServiceError (ServiceError' {_serviceAbbrev = Abbrev "S3", _serviceStatus = Status {statusCode = 404, statusMessage = "Not Found"}, _serviceHeaders = [("x-amz-request-id","XXX"),("x-amz-id-2","XXX"),("Content-Type","application/xml"),("Transfer-Encoding","chunked"),("Date","Thu, 04 Apr 2019 08:22:59 GMT"),("Server","AmazonS3")], _serviceCode = ErrorCode "NoSuchKey", _serviceMessage = Just (ErrorMessage "The specified key does not exist."), _serviceRequestId = Just (RequestId "12FBC8A6A52E04F7")})
````

**Suggested behavior**

**Why would the enhancement be useful to most users**

    [Explain why the enhancement would be useful to most users, list some use cases]

**Rome version:** 

`blender/tap/rome: stable 0.20.0.56`

**OS and version:** 

macOS Mojave `10.14.4 (18E226)`

**Comment by blender** [comment]
Errors are cache misses. You're totally fine.

bcsymbolmap  ids are for all platform but of course if you either don't upload them or you don't build for all platfroms you won't have them. Hence the "error".

I should really rename this to Warning :)

**Comment by leviathan** [comment]
@blender renaming this to `warning` would be helpful, or even `info` might be sufficient.
Or even hide these messages behind a `--verbose` command.
