### ISSUE TITLE
Possible for Google Cloud Storage support as things stand?

### ISSUE THREAD

**Issue by ekimia** [blender/Rome#182]
I know theres currently a task to implement GCS support, but given they share the same S3 protocol, is there a way to get it working as things stand?

**Comment by blender** [comment]
I never tried. It might work by setting the endpoint override just as for Minio https://github.com/blender/Rome/blob/master/README.md#setting-up-endpoint-override

**Comment by blender** [comment]
In case you want to try let me know the results. Also pay attention to the fine print, __do not remove the region__

**Comment by blender** [comment]
@ekimia Thanks to @BalestraPatrick  you can now use w[hatever backend you want](https://github.com/blender/Rome/#custom-engine). https://github.com/blender/Rome/pull/185

**Comment by blender** [comment]
You can try the pre-release at: https://github.com/blender/Rome/releases/tag/v0.22.0.59

**Comment by ekimia** [comment]
awesome @blender and @BalestraPatrick !!! Been slammed dealing with company launch but i will verify + add a PR to the readme explaining how to use GCS

**Comment by blender** [comment]
@ekimia even better, you can contribute the script itself 🤓
