### ISSUE TITLE
Cannot use Rome with Minio

### ISSUE THREAD

**Issue by olejnjak** [blender/Rome#186]
## Enhancement Suggestion / Bug Report 

Since the latest version (0.21.0.58) I am unable to use Rome anymore, I get error 
```
Error: could not download FirebaseAnalytics.dSYM : The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.
```

**Steps which explain the enhancement or reproduce the bug**

1. `rome download`

**Current behavior**

I get error 
```
Error: could not download FirebaseAnalytics.dSYM : The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint.
```

**Suggested behavior**

Should work like previous versions

**Rome version:** 

0.21.0.58

**OS and version:** 

macOS 10.14.5 Mojave

**Comment by blender** [comment]
Hello, this is a problem with Minio and the bucket configuration you have. https://github.com/minio/minio/issues/4681

**Comment by olejnjak** [comment]
Okay

**Comment by joshuapoq** [comment]
@blender This issue is not present with `v0.20.0.56` but is present in `v0.21.0.58`.

> This seems to work fine! Hopefully I didn't break any other mechanism and there are enough tests to prove that.
Famous last words in the end of PR #175 ? 😅

**Comment by blender** [comment]
Yeah, maybe. Thing is I also use Minio in integration tests. Everything is working there so it would be great if you would help me reproduce.

**Comment by joshuapoq** [comment]
I have it reproduced with the newer version and am currently investigating - not ruling out that it's an issue with our config. Will post once I find out!

**Comment by blender** [comment]
Can you take a look at any of my bats test in the integration folder? That is how I spin up Minio.
