### ISSUE TITLE
"The AWS Access Key Id you provided does not exist in our records" on minio instances.

### ISSUE THREAD

**Issue by codeOfRobin** [blender/Rome#187]
## Bug Report 

I'm getting a `The AWS Access Key Id you provided does not exist in our records` error when trying to upload/download to our minio instance. I've confirmed that they keys are indeed correct (they work for the web app)

**Steps which explain the enhancement or reproduce the bug**

1. Setup a new minio.io instance
2. Try uploading via rome once (that seems to work)
3. Try uploading/downloading, it'll fail with a "The AWS Access Key Id you provided does not exist in our records" error

**Current behavior**

Uploads and Downloads do not work with minio.io instance

**Rome version:** 

`0.21.0.58 - Romam uno die non fuisse conditam.`

**OS and version:** 

`macOS Mojave 10.14.5 Beta (18F131a)`

**Comment by codeOfRobin** [comment]
Also, I can confirm that this command does indeed work on `v0.20.0.56` which means it's probably a regression in the latest version.

**Comment by blender** [comment]
Can you check if you have a combination of env variable and config file ?

**Comment by codeOfRobin** [comment]
We just have the config/credential files at `~/.aws`

**Comment by blender** [comment]
Ok, I will take a look. Seems odd as I’m also using credential file and I can’t see how it would be different when using Minio or S3.

**Comment by itsthejb** [comment]
Hi everyone,

Just trying Rome for the first time, and hitting this issue. All AWS config appears to be correct, and I can use `aws s3` commands with the same config. Reverting to version `0.20.0.56` works as expected. So regression, or docs need updating?

**Comment by blender** [comment]
I can not reproduce the issue neither on CI nor on my local setup. If anyone has and idea how to, I would be more than glad to solve it. 

Please take a look as the basts tests setup for reference.

**Comment by itsthejb** [comment]
Interestingly, I'm now trying to use env vars for credentials to test on our build server (BuddyBuild), and passing the credentials are variables causes this error on `0.20.0.56`, where pasting the same credentials into `~/.aws/credentials`, etc. works fine. Also tried quoting the strings, and got the same errors

**Comment by blender** [comment]
I think I have identified the problem on `0.23.0.60`. Not sure about the other versions. As you can see from [here](https://github.com/blender/Rome/blob/b79a73e91eb957111b1d8742e41a1a3d10ffcd9e/integration-tests/current-framework-yml.bats#L58) I'm also using env variables

**Comment by itsthejb** [comment]
My issue appears to be https://github.com/blender/Rome/issues/102. Which seems to boil down to blender needing to have the vars `export`ed. This would require re-`export`ing vars from the build server; which is rather messy. Currently I'm working around this by writing the vars to `~/.aws`:

```
mkdir -p ~/.aws
echo -n "[default]\nregion = $AWS_REGION\n" > ~/.aws/config
echo -n "[default]\naws_access_key_id = $AWS_ACCESS_KEY_ID\naws_secret_access_key = $AWS_SECRET_ACCESS_KEY\n" > ~/.aws/credentials
```

**Comment by blender** [comment]
Le't move to #102

**Comment by blender** [comment]
never use type aliases 

```diff
-          >>= flip getEndpointFromFile (fromMaybe "default" profile)
+          >>= getEndpointFromFile (fromMaybe "default" profile)
```
