### ISSUE TITLE
S3 - Moving role_arn from `credentials` to `config`

### ISSUE THREAD

**Issue by popei69** [blender/Rome#189]
## Enhancement Suggestion / Bug Report 

Going further in https://github.com/blender/Rome/issues/175, the fix seems to rely on `credentials` file only for `source_profile` and `role_arn` fields.

However, AWS suggests to use `config` to setup `source_profile` and `role_arn`. Source: [Assuming an IAM Role in the AWS CLI](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-role.html)

**Steps which explain the enhancement or reproduce the bug**

1. Setup AWS with `source_profile` and `role_arn` setup in `config` file as expected by AWS from their documentation.
2. Run Rome

**Current behavior**

    Access Denied

**Why would the enhancement be useful to most users**

Using `config` file instead of `credentials` file for this specific request would avoid to support duplicated configuration between those two files.

**Rome version:** 

    0.21.0.58 - Romam uno die non fuisse conditam.

**OS and version:** 

    macOS 10.14.4

**Comment by blender** [comment]
Yes, it relies on `~/.aws/credentials`. I was under the impression that was the correct place but apparently it's not. I'll address this asap.

**Comment by popei69** [comment]
@blender I had a look into it and created a PR for it #190. 

It ran in my local environment with having the `source_profile` and `role_arn` only in config file instead of credentials. I'm not expert into Haskell, please let me know if I miss anything.

Thanks

**Comment by blender** [comment]
@popei69 Thanks for you contribution, the new version is out https://github.com/blender/Rome/releases/tag/v0.23.0.60

**Comment by popei69** [comment]
@blender No worries, happy to help! Thanks for the quick release.
