### ISSUE TITLE
Refactor Stringly Typed Functions to Properly typed functions

### ISSUE THREAD

**Issue by blender** [blender/Rome#25]
Refactor all the `type Something = String` to `newtype Something = Something String`

**Steps which explain the enhancement**

1) In Data.Cartfile refactor:
```
type Location = String
type Version = String
```
to
```
newtype Location = Location String
newtype Version = Version String
```
2) In Data.Romefile refactor:
```
type FrameworkName = String
type GitRepoName = String
```
to
```
newtype FrameworkName = FrameworkName String
newtype GitRepoName  = GitRepoName String
```

3) Adapt the remaining code to the new types

**Current and suggested behavior**

Currently some functions are _stirngly_ typed and this leads to quite some confusion around them.
For example in [deriveFrameworkNameAndVersion](https://github.com/blender/Rome/blob/master/src/Lib.hs#L222) the return type is `[(FrameworkName, Version)]` which is just an alias for `[(String, String)]`. This is not optimal as it's possible to mix up `FrameworkName` with `Version` later down then code.

If `FrameworkName` and `Version` were defined using `newtype` instead of `type` mixing `FrameworkName` and `Version` would not be possible.

**Rome version:** v.0.6.1.11
**OS and version:** MacOSX 10.11.6 - El Capitan

**Comment by 2016rshah** [comment]
I'd be happy to work on this!

**Comment by blender** [comment]
@2016rshah Please go ahead.

**Comment by blender** [comment]
@2016rshah Once you are done I can open another issue and  if you know QuickCheck you could write some test for the refactored code too.

**Comment by blender** [comment]
@2016rshah Thanks for your contribution!
