### ISSUE TITLE
Rome upload does not accept repository name (if differs from framework name)

### ISSUE THREAD

**Issue by erichoracek** [blender/Rome#30]
**Current behavior**

Cartfile:
```
github "bitstadium/HockeySDK-iOS"
```

Romefile:
```
[RepositoryMap]
    HockeySDK-iOS = HockeySDK
```

When building with Carthage:

```
$ carthage build HockeySDK-iOS --platform ios
*** Building scheme "HockeySDK Framework" in HockeySDK.xcodeproj
```

The following is produced: `Cartage/Build/iOS/HockeySDK.framework*`

However, unlike Carthage, the repo name does not work when passed to `rome upload`

```
$ rome upload HockeySDK-iOS
(nothing uploaded)
```

If the Framework name is specified, it does work:

```
$ rome upload HockeySDK
Successfully uploaded HockeySDK to: HockeySDK/HockeySDK.framework-4.1.2.zip
Successfully uploaded HockeySDK.dSYM to: HockeySDK/HockeySDK.framework.dSYM-4.1.2.zip
```

As such, `rome upload` doesn't function the same way as Carthage, which is what users would expect in this scenario (repository names are provided, not framework names)

**Expected behavior**

The `upload` command should take repository names, not framework names.

**Rome version:** 0.6.0.10
**OS** macOS sierra 10.12

**Comment by blender** [comment]
@erichoracek How would this play with the multiple aliases? 

```
[RepositoryMap]
    awesome-cats = Caturday, CatCore
```

I assumed that one might want to upload just CatCore and not Caturday

**Comment by erichoracek** [comment]
@blender Since there is no way to tell Carthage to only build a single framework from a repository, I'm not sure this should be the default behavior. From your hypothetical example, invoking `carthage build` would produce both `Caturday` and `CatCore`. I can't think of a scenario in which you wouldn't want to cache both of these products. Even if there is one, perhaps it should be be an additional parameter, e.g.:

```
rome upload --framework Caturday
```

But the default would still be:
```
rome upload awesome-cats
```

Which would upload both `Caturday` and `CatCore`.

**Comment by blender** [comment]
@erichoracek Thanks for you input. I'll need some time to think about what impact this has on the existing code/logic.

**Comment by blender** [comment]
@erichoracek  please try pre-release [v0.7.0.12](https://github.com/blender/Rome/releases/tag/v0.7.0.12)

**Comment by erichoracek** [comment]
Appears to be working, thanks!
