### ISSUE TITLE
Allow for certain repositories to be ignored entirely

### ISSUE THREAD

**Issue by erichoracek** [blender/Rome#31]
Some repositories use Carthage as a simple mechanism to include other git repositories that do not produce frameworks. Even Carthage itself does this, to include [xcconfigs](https://github.com/Carthage/Carthage/blob/master/Cartfile.private#L3).

To accommodate for this existing paradigm, Rome should allow for certain repositories to be omitted entirely from the upload/download/list commands.

One could imagine that this would be an addition to the `Romefile`, along the same lines as the existing `RepositoryMap` section. Perhaps it could be named something along the lines of `Ignored`.

As a hypothetical example, let's imagine the following:

Cartfile:
```
github "Quick/Nimble"
github "jspahrsummers/xcconfigs"
```

Romefile:
```
[Ignored]
    xcconfigs
```

We then perform the following commands:

```
$ rome upload
Successfully uploaded Nimble to: Nimble/Nimble.framework-5.0.0.zip
Successfully uploaded Nimble to: Nimble/Nimble.framework.dSYM-5.0.0.zip
```

```
$ rome list
Nimble 5.0.0 ✔︎
```

```
$ rome download
Donwloaded: Nimble.framework-5.0.0.zip
Unzipped: Nimble.framework-5.0.0.zip
Donwloaded: Nimble.framework.dSYM-5.0.0.zip
Unzipped: Nimble.framework.dSYM-5.0.0.zip
```

Note that `xcconfigs` was never included in any of the hypothetical output.

#### Current Behavior: 

Currently, in scenarios like these, users have to manually filter out repositories that fall into this category, since otherwise they will always show up when invoking `rome list --missing`.

While less of a hassle, this also pollutes the output of the download command with errors that will never be resolved:

```
$ rome download
...
Error downloading xcconfigs.framework-cc451b08e052b6146f5caf66bc1120420c529c7b.zip : The specified key does not exist.
Error downloading xcconfigs.framework.dSYM-cc451b08e052b6146f5caf66bc1120420c529c7b.zip : The specified key does not exist.
```

**Comment by blender** [comment]
Sounds good.

**Comment by blender** [comment]
@erichoracek Some clarification is needed

In the light of #30  adding an ignore section will look like this:
```
[IgnoreMap]
  xcconfigs = xcconfigs
  awesome-cat-names = CatCore
```
This allows selective ignoring when using aliases #12 

Can this do?

**Comment by erichoracek** [comment]
@blender sure, this will work

**Comment by blender** [comment]
@erichoracek please try [v0.7.1.13](https://github.com/blender/Rome/releases/tag/v0.7.1.13)

**Comment by blender** [comment]
@erichoracek  seems to work as expected over here, do you have any input?

**Comment by erichoracek** [comment]
@blender Appears to be working perfectly—thanks for taking a stab at this. Rome has been a joy to use.

**Comment by blender** [comment]
Thank, maybe you have input on #38
