### ISSUE TITLE
Add support for uploading resulting build

### ISSUE THREAD

**Issue by wuntunsun** [blender/Rome#37]
#### Enhancement Suggestion

    When making changes to an existing framework, which is to be integrated into another framework or app, it is not possible to upload it as Rome only refers to the Cartfile.resolved and not the actual framework being built. This means that the framework in question must first be checked out and built in some other context.

    **Steps which explain the enhancement**

    1. Modify a framework.
    2. Build the framework.
    3. Call Rome upload

    **Current and suggested behaviour**

    The current behaviour is that only those frameworks referenced from the Cartfile.resolved are considered. The new behaviour would be that the framework being worked on would also be uploaded.

    **Why would the enhancement be useful to most users**

   The enhancement would facilitate interim modifications and their testing in the working environment. It would remove the redundant step of building again in the calling context for both interim and final versions.

    **Rome version:** 0.6.0.9
    **OS and version:** Mac OSX, 10.11.6

**Comment by blender** [comment]
could this be a duplicate of #24 ?

**Comment by wuntunsun** [comment]
Yes, it is an exact duplicate. I eagerly await it!
