### ISSUE TITLE
Feature Local Cache 

### ISSUE THREAD

**Issue by netbe** [blender/Rome#38]
#### Enhancement Suggestion

   Would be great to have a local cache directory instead of AWS
    **Steps which explain the enhancement**

```
1. Check if product is in local cache
2. Check if product is in AWS
3. Continue with normal behavior

**Current and suggested behavior**
```

  sometimes, it takes too much time to fetch on aws

```
**Why would the enhancement be useful to most users**

sometimes, it takes too much time to fetch on aws

**Rome version:** -
**OS and version:** -
```

**Comment by blender** [comment]
Suggested Implementation:

```
[Cache]
 S3-Bucket =  some-bucket-name
 local = /some/__absolute__/path
```

Now, if you don't want to use the local cache you can remove the key from the Romefile.

Should also a flag be provided to ignore the local cache in case it's specified?

**Comment by blender** [comment]
Done with suggested implementation
