### ISSUE TITLE
Support for carthage --cache-builds flag

### ISSUE THREAD

**Issue by t089** [blender/Rome#47]
Hey,

carthage 0.20.0 introduced the `--cache-builds` flag, which generates `.NAME.version` [version files](https://github.com/Carthage/Carthage/blob/master/Documentation/VersionFile.md) for each built framework. When building a dependency carthage will use these version files to check if a corresponding build artefact is already available and skip the build. Would be great if rome could store these version files alongside the frameworks in the S3 cache and restore them during a `rome download`.

Thank you!

**Comment by blender** [comment]
Interesting, I will take a look at that.

**Comment by blender** [comment]
@t089 Maybe I ask what the use case for this is?

Usually the workflow with rome resembles the following:
```
rome download --platform iso && rome list --missing --platform ios | awk '{print $1}' | xargs carthage build --platform ios
```

**Comment by t089** [comment]
Very good questing. Let me explain:

Say you have a dependency **FrameworkA** that itself depends on **FrameworkB** and **FrameworkC**.

Now, **FramworkA** needs an update. In your example Rome would fail to download  **FramworkA** from cache and would trigger a carthage build. Carthage would then build **FrameworkA** but would also build its dependencies **FrameworkB** and **FrameworkC**, although they did not change and are already present in the `Build/` folder (because Rome downloaded them). With the new `--cache-builds` option carthage can reuse the existing **FrameworkB** and **FrameworkC** build artefacts, **but** only if the corresponding version file exists.

We are working a lot with internal frameworks that are included in the main app as carthage dependencies. Our frameworks also have some 3rd party dependencies and it's always painful to watch carthage build stuff that is already there waiting to be used...

**Comment by blender** [comment]
@t089 I understand. Thanks for explaining, I think we have the same issue but never noticed.

Do you have any opinion on the implementation details I have made a note of to myself in the first comment?

**Comment by blender** [comment]
Please try pre-release https://github.com/blender/Rome/releases/tag/v0.10.0.21

Let me know if it works as expected and I will proceed with a full release.

**Comment by t089** [comment]
Awesome, that was quick, nice work. May I ask which route of implementing it you chose?  I ran a quick test `rome upload` and it reported `Uploaded .Xy.version to: Xy/.Xy.version-3.3.1`. But `rome download xy` did not seem to restore the version file locally.

**Comment by blender** [comment]
I implemented the following:

- Version Files are uploaded to `<git-repo-name>/.<git-repo-name>.version-<carthage-resolved-version-hash>`
- Version Files are restored to `Carthage/Build`

Seems to work for me, I'm running:

```
$ rm  Carthage/Build/.KeychainAccess.version #remove the original version

$ rm ~/Library/Caches/Rome/KeychainAccess/.KeychainAccess.version-v2.4.0 #remove the local cached version

$ rome download KeychainAccess --platform iOS -v #download framework
09:07:12 2017-03-20 - Found KeychainAccess in local cache at: /Users/blender/Library/Caches/Rome/KeychainAccess/iOS/KeychainAccess.framework-v2.4.0.zip
09:07:12 2017-03-20 - Staring to unzip KeychainAccess.framework-v2.4.0.zip
09:07:12 2017-03-20 - Unzipped KeychainAccess from: KeychainAccess.framework-v2.4.0.zip
09:07:12 2017-03-20 - Found KeychainAccess.dSYM in local cache at: /Users/blender/Library/Caches/Rome/KeychainAccess/iOS/KeychainAccess.framework.dSYM-v2.4.0.zip
09:07:12 2017-03-20 - Staring to unzip KeychainAccess.framework.dSYM-v2.4.0.zip
09:07:12 2017-03-20 - Unzipped KeychainAccess from: KeychainAccess.framework.dSYM-v2.4.0.zip
09:07:12 2017-03-20 - Started downloading .KeychainAccess.version from: KeychainAccess/.KeychainAccess.version-v2.4.0
09:07:21 2017-03-20 - Downloaded 0.0 MB of 0.0 MB for .KeychainAccess.version
09:07:21 2017-03-20 - Downloaded .KeychainAccess.version from: KeychainAccess/.KeychainAccess.version-v2.4.0
09:07:21 2017-03-20 - Copying .KeychainAccess.version to: /Users/blender/Library/Caches/Rome/KeychainAccess/.KeychainAccess.version-v2.4.0

$ ls Carthage/Build/.KeychainAccess.version 
-rw-r--r--  1 blender  staff   661B Mar 20 09:07 Carthage/Build/.KeychainAccess.version

**Comment by t089** [comment]
Oh, boy was probably too early in the morning 💤, of course I was using the pre-release version binary only for the upload but not for the download command. Ok, seems to work for me as well. Thank you 👍

**Comment by blender** [comment]
Great, I will test a little more and hopefully promote the tag to full release :)

@t089 Thanks for suggesting this feature. I look forward to hear more feedback.

**Comment by blender** [comment]
Looks like it's working. Full release it is!
