### ISSUE TITLE
Add Support for Google Cloud Storage

### ISSUE THREAD

**Issue by blender** [blender/Rome#49]
#### Enhancement Suggestion

Add support for Google Cloud Storage

**Current and suggested behavior**

Currently only Amazon's S3 is supported as remote storage. Supporting Google Cloud Storage would allow users on the Google Cloud to use Rome too

**Why would the enhancement be useful to most users**

Supporting Google Cloud Storage  would allow users on the Google Cloud to use rome too.

**Comment by blender** [comment]
Use this library: https://github.com/brendanhay/gogol

**Comment by RafaelPlantard** [comment]
Are you developing it or can I start to do it?

**Comment by blender** [comment]
@RafaelPlantard I have done some work here https://github.com/blender/Rome/pull/148. 

I think the direction I was going with was to call the engine scripts with the path to the binary to upload and where to upload it, hiding all the rest of the logic for now.


I updated the branch with the latest changes from master so at least it's compiling.

**Comment by RafaelPlantard** [comment]
I will take a look...

**Comment by blender** [comment]
@RafaelPlantard  if you are having trouble building, see https://github.com/blender/Rome/issues/158#issuecomment-441460926

**Comment by RafaelPlantard** [comment]
Are you reading my mind? I'm facing some troubles with install Brittany, too

**Comment by RafaelPlantard** [comment]
I'm super beginner in Haskell, is there a good material to beginners?

**Comment by blender** [comment]
http://haskellbook.com or http://www.cs.nott.ac.uk/~pszgmh/pih.html

However implementing #146 might be not the best beginner task.

**Comment by blender** [comment]
@RafaelPlantard Thanks to @BalestraPatrick  you can now use [whatever backend you want](https://github.com/blender/Rome/#custom-engine)

**Comment by blender** [comment]
You can try the pre-release at: https://github.com/blender/Rome/releases/tag/v0.22.0.59
