### ISSUE TITLE
Unable to download after upload

### ISSUE THREAD

**Issue by o2x7** [blender/Rome#53]
Some of my frameworks are missing the platform directory and cannot be downloaded after a successful upload

For example, I execute the following command and get a success message:
```
rome upload --platform ios amp.ios
Uploaded .amp.ios.version to: amp.ios/.amp.ios.version-2.27
```

I can see on AWS, the file exists under /amp.ios/.amp.ios.version-2.27

When i attempt to download the file I get an error:
```
rome download amp.ios
The specified key does not exist.
```

But i have another framework that works just perfect:
```
rome upload --platform ios libzeus
Uploaded libzeus to: libzeus/iOS/libzeus.framework-2.70.zip
```

I can see on AWS, the file exists under /libzeus/iOS/.libzeus.version-2.70
```
rome download --platform ios libzeus
Downloaded libzeus from: libzeus/iOS/libzeus.framework-2.70.zip
```

Why would one of these use a different path structure and work?

    **Rome version:** 0.10.0.21
    **OS and version:** OSX Sierra - 10.12.3

**Comment by blender** [comment]
Can it possibly be that you are mixing to things?

In your first example I see that reported uploaded is a `.version` file. This is not your frameworks but just the `.version` [information that Carthage builds](https://github.com/Carthage/Carthage/blob/master/Documentation/VersionFile.md) when using `--cache-builds`. The location of this file in the remote cache mirrors the location of where Carthage puts it on disk. This is at the root of `Carthage/Build` directory and not inside each platform directory.

In your second example you are asking rome to download for all platforms but before you uploaded just for one, naturally the framework won't exist at path where you haven't uploaded.

In your last 2 examples you are both uploading and downloading with the same platform specified so everything works out.


@o2x7  Does this explain what you are experiencing?

**Comment by blender** [comment]
Please try: https://github.com/blender/Rome/releases/tag/v0.10.1.22

**Comment by blender** [comment]
@o2x7 did you have a chance to try out the version above?  

You can also try this version https://github.com/blender/Rome/releases/tag/v0.10.2.24 . The binary is attached as a zip file.

**Comment by blender** [comment]
@o2x7 Any update? This is another release you can try https://github.com/blender/Rome/releases/tag/v0.11.0.27 . I will close the issue in a few days if I don't hear back. Feel free to comment even if closed and I will open it again.

**Comment by RafaelPlantard** [comment]
I guess I'm facing the same issue, I always upload always with success, but when I try to download:
```
➜  BikeToWork git:(master) rome download --platform iOS --cache-prefix "${cachePrefix}" Alamofire
Found Alamofire in local cache at: /Users/rafael/Library/Caches/Rome/swiftlang-1000.11.42-clang-1000.11.45.1/Alamofire/iOS/Alamofire.framework-4.8.0.zip
Found Alamofire.A0121347-8CEF-3EB0-9333-17687B32A755.bcsymbolmap in local cache at: /Users/rafael/Library/Caches/Rome/swiftlang-1000.11.42-clang-1000.11.45.1/Alamofire/iOS/Alamofire.framework-4.8.0.zip
Found Alamofire.FABB4B33-26EB-31B5-A31A-572FEB6CA4B9.bcsymbolmap in local cache at: /Users/rafael/Library/Caches/Rome/swiftlang-1000.11.42-clang-1000.11.45.1/Alamofire/iOS/Alamofire.framework-4.8.0.zip
Error: could not find Alamofire.4F44D10A-A8AB-3356-BF7B-A044310EB51C.bcsymbolmap in local cache at : /Users/rafael/Library/Caches/Rome/swiftlang-1000.11.42-clang-1000.11.45.1/Alamofire/iOS/4F44D10A-A8AB-3356-BF7B-A044310EB51C.bcsymbolmap-4.8.0.zip
Error: could not find Alamofire.53D18DCF-FA8E-3380-9198-95B28455CDE7.bcsymbolmap in local cache at : /Users/rafael/Library/Caches/Rome/swiftlang-1000.11.42-clang-1000.11.45.1/Alamofire/iOS/53D18DCF-FA8E-3380-9198-95B28455CDE7.bcsymbolmap-4.8.0.zip
Error: could not download Alamofire.4F44D10A-A8AB-3356-BF7B-A044310EB51C.bcsymbolmap : ServiceError (ServiceError' {_serviceAbbrev = Abbrev "S3", _serviceStatus = Status {statusCode = 404, statusMessage = "Not Found"}, _serviceHeaders = [("x-amz-request-id","95F37BC080D3E1C7"),("x-amz-id-2","szZRHR/2PMB4D8Vydy8KL9HsXhVRB4sKjaAZ1vqzzBGHUI1hS+quE8v10BTvvRo7xP3gNih0yFI="),("Content-Type","application/xml"),("Transfer-Encoding","chunked"),("Date","Sun, 16 Dec 2018 02:52:29 GMT"),("Server","AmazonS3")], _serviceCode = ErrorCode "NoSuchKey", _serviceMessage = Just (ErrorMessage "The specified key does not exist."), _serviceRequestId = Just (RequestId "95F37BC080D3E1C7")})
Error: could not download Alamofire.53D18DCF-FA8E-3380-9198-95B28455CDE7.bcsymbolmap : ServiceError (ServiceError' {_serviceAbbrev = Abbrev "S3", _serviceStatus = Status {statusCode = 404, statusMessage = "Not Found"}, _serviceHeaders = [("x-amz-request-id","C0F98EE368BD2B8F"),("x-amz-id-2","A1FIFVJSwhiGfrYVNGz97FzxGX2WZ8QkGKeGqtvI/HDnoTZTvzzJZ9iEf/gU4o4BA+uu+jcP+lQ="),("Content-Type","application/xml"),("Transfer-Encoding","chunked"),("Date","Sun, 16 Dec 2018 02:52:30 GMT"),("Server","AmazonS3")], _serviceCode = ErrorCode "NoSuchKey", _serviceMessage = Just (ErrorMessage "The specified key does not exist."), _serviceRequestId = Just (RequestId "C0F98EE368BD2B8F")})
Found Alamofire.dSYM in local cache at: /Users/rafael/Library/Caches/Rome/swiftlang-1000.11.42-clang-1000.11.45.1/Alamofire/iOS/Alamofire.framework.dSYM-4.8.0.zip
Found .Alamofire.version in local cache at: /Users/rafael/Library/Caches/Rome/swiftlang-1000.11.42-clang-1000.11.45.1/Alamofire/.Alamofire.version-4.8.0
Copied .Alamofire.version to: Carthage/Build/.Alamofire.version
```
