### ISSUE TITLE
Missing executable permission to framework

### ISSUE THREAD

**Issue by yuriferretti-luizalabs** [blender/Rome#57]
When downloading files from cache the Module.framework/Module file doesn't have executable permission, this leads to `library not loaded crashes`
Just adding the missing executable permission fix this issue.

**Comment by blender** [comment]
Hi @yuriferretti-luizalabs , what platform is this?

**Comment by yuriferretti-luizalabs** [comment]
@blender I'm building/caching for iOS platform

**Comment by blender** [comment]
Thanks, it's the first time I hear of this this problem. Are you sure this is not related to this: https://github.com/blender/Rome/issues/56 specifically you are not building frameworks at all but just relaying on Rome leading to this: https://github.com/Palleas/bookish-invention/pull/1#event-1028177117  ?

**Comment by yuriferretti-luizalabs** [comment]
I don't think so, because I didn't change anything related to `Always Embed Standard Libraries` nor framework copy / linking. I just compared carthage build output with rome cache output and noticed that all `Carthage/Build/iOS/{framework-name}.framework/{framework-name}` in rome cache were missing executable permission.
Then I executed `find Carthage/Build/iOS/" --name "*.framework" | xargs chmod -R +x` and everything worked like a charm using rome cache.

**Comment by blender** [comment]
I have checked my local cache and I also don't have +x permissions on downloaded frameworks but everything works fine for me.

What version of Xcode are you using?

**Comment by yuriferretti-luizalabs** [comment]
I'm using `Xcode 8.3`

**Comment by blender** [comment]
Ok, thanks. I am using Xcode 8.2.1, that might be the problem.

**Comment by yuriferretti-luizalabs** [comment]
Tell me if you need some help, I'll be glad helping you to improve this awesome lib!

**Comment by blender** [comment]
Thanks, I could use some help if you want to take it. It would involve probably using https://hackage.haskell.org/package/turtle to run chmod 

Let me know if you want to try your luck :)

**Comment by blender** [comment]
Please try pre-release https://github.com/blender/Rome/releases/tag/v0.10.2.24

If you confirm I will make a full release.

**Comment by yuriferretti-luizalabs** [comment]
@blender how can install this version ?

**Comment by blender** [comment]
@yuriferretti-luizalabs download from here: https://github.com/blender/Rome/releases/download/v0.10.2.24/rome.zip

- Copy it to the folder where you project is and run `./rome --version` be sure it says 0.10.2.24
- Run then `./rome ...`  command that you desire

**Comment by blender** [comment]
@yuriferretti-luizalabs Did you have a chance to try out the fix?

**Comment by yuriferretti-luizalabs** [comment]
@blender I just tested and everything is working like a charm!!!

**Comment by blender** [comment]
Great, I'll make a full release then! Thank you very much!

**Comment by blender** [comment]
There is a full new release that includes this fix and #58  , get it with `brew upgrade rome`
