### ISSUE TITLE
Can I use local cache only?

### ISSUE THREAD

**Issue by muukii** [blender/Rome#61]
I want to use **Rome** as local cache only.
That is useful when I using git-worktree.

**Comment by blender** [comment]
This is certainly doable.

However how do you see this working with the remote cache? 

1) How would the list command work? Should a cache specifier be added (--local, --remote=s3)?
2) Do you expect any changes in upload/download behaviour when both a local and a remote cache are specified?
3) If just a local cache is specified how should `upload/download --skip-local-cache work`? Do nothing?

**Comment by blender** [comment]
@muukii If you need to use the feature "right now" as a work-around you can just provide fake AWS credentials and a fake name for the S3-Bucket. Then use the normal upload/download commands. Rome will fail uploading to the network but should copy to/from your local cache.

**Comment by muukii** [comment]
@blender 
Thank you. I'll try that work-around.

I think that Rome should have `--local-only` option.
if Rome received `--local-only` option then cache to local only.
if Rome received no option then cache to both remote and local.

**Comment by caynan** [comment]
I would love to see this feature, I'm willing to help implement it, I just need some initial guidance.

**Comment by blender** [comment]
@muukii  @caynan I'm at work on it but it's requiring some major code refactoring to avoid a ton of duplication.

@caynan Thank for the availability, you can follow the progress here: https://github.com/blender/Rome/pull/63

**Comment by blender** [comment]
@muukii @caynan please try pre-release https://github.com/blender/Rome/releases/tag/v0.11.0.25

in your Romefile you can just specify `local = some/path/` in the `[Cache]` section. The `S3-Bucket` key is now optional. If you have both keys specified you get the old behaviour.

**Comment by caynan** [comment]
@blender I will try it in a bit, you're the best. I'm sorry I couldn't help you, I realized the code base is in Haskell and I don't have any knowledge of it :/

**Comment by blender** [comment]
@caynan Thanks, I am glad of your appreciation. I encourage you to try your hand at Haskell :) Let me know if you encounter any bugs with this version.

**Comment by muukii** [comment]
@blender whoa! Thank you!  I'll try it!

**Comment by blender** [comment]
Released in https://github.com/blender/Rome/releases/tag/v0.11.0.27
