### ISSUE TITLE
Rome places files within frameworks individually rather than replacing entire framework on download

### ISSUE THREAD

**Issue by erichoracek** [blender/Rome#64]
Currently, when you download a framework that has less files than what's on disk, Rome will leave the old files in place within the framework's directory structure.

For example, in CocoaLumberjack 3.2.0, the `DDOSLogger.h` file was added. If you have CocoaLumberjack 3.2.0 on disk, and perform a `rome download CocoaLumberjack` (with your Cartfile.resolved containing version 3.1.0), the `DDOSLogger.h` file will remain on disk. However, when you perform a build, you will get a failure with the following error:

```
<module-includes>:1:1: Umbrella header for module 'CocoaLumberjack' does not include header 'DDOSLogger.h'
```

Once you remove the `DDOSLogger.h` file from disk, the build continues within errors.

**Rome version:** 0.10.2.24 - Romam uno die non fuisse conditam.
**OS Version** macOS 10.12.4 (16E195)

**Comment by erichoracek** [comment]
For example, `rsync`'s handles this via its `--delete` parameter:

```
--delete                delete extraneous files from dest dirs
```

However, I can't think of a reason why you wouldn't want this behavior with `rome`.

**Comment by blender** [comment]
Got it. The solution is to simply delete the current framework folder before unpacking. I don't believe there is a reason to a an explicit flag for this. It should be the only behaviour acceptable.

**Comment by blender** [comment]
@erichoracek  please try pre-release v0.11.0.26 at https://github.com/blender/Rome/releases/tag/v0.11.0.26

**Comment by blender** [comment]
@erichoracek  Any feedback?

**Comment by erichoracek** [comment]
Tried it out, looks good to me!

**Comment by blender** [comment]
all right, off we go with a release then!
