### ISSUE TITLE
Romefile RepositoryMap does not work with github references

### ISSUE THREAD

**Issue by erichoracek** [blender/Rome#7]
It would appear that the Romefile repository map doesn't work with github references—only with git references. It seems to have to do with the `deriveFrameworkName` function at https://github.com/blender/Rome/blob/master/src/Lib.hs#L192, which doesn't appear to be using the `romeMap` to do a repo to framework lookup. This results in the `Romefile` mappings being unused when they are mapping from a github repo name to a framework name.

**Comment by blender** [comment]
To clarify, I understand that your scenario is as follows:

In your Cartfile.resolved:

```
github "myAnimalStartup/Awesome-cat-names" "3.4.1"
```

But your framework name is actually __not__ Awesome-cat-names but something else.

Correct?

**Comment by blender** [comment]
Please try pre-release https://github.com/blender/Rome/releases/tag/v0.4.0.4

**Comment by blender** [comment]
@erichoracek  any feedback?

**Comment by erichoracek** [comment]
This build appears to have fixed the issue—thanks again for the responsiveness! Everything now seems to be working beautifully ✨

**Comment by blender** [comment]
Great! I will make one more change to the Romefile format to align it with the INI file format and then make a stable realease. This will require changing the old Romefile. Sorry for that.

**Comment by blender** [comment]
@erichoracek v0.4.0.5 with GitHub reference and [Romefile ini](https://github.com/blender/Rome/blob/93fcb22698993625fc5bba20b7589c0623dd1f79/README.md) is out. Please try, beware that the format of the Romefile has changed.

- Section `[S3-Bucket]` is now called `[Cache]`
- Section `[Cache]` __must__ contain a key called `S3-Bucket`
- Key-Value format is now `key = value`

Please see Romefile section in [README.md](https://github.com/blender/Rome/blob/93fcb22698993625fc5bba20b7589c0623dd1f79/README.md)
