### ISSUE TITLE
Add JSON output format to list command

### ISSUE THREAD

**Issue by blender** [blender/Rome#78]
#### Enhancement Suggestion

Add the possibility to output the results of the list command as JSON

**Steps which explain the enhancement**

1. Add an optional argument to `list` (perhaps `--print-format=JSON`)
1. Devise a JSON representation for `list` command output

**Current and suggested behavior**

Currently the only output format is a custom text representation

**Why would the enhancement be useful to most users**

This enhancement would allow for more flexibility when integrating Rome into other workflows

**Comment by pt2121** [comment]
hey @blender, I'll give this a shot.

**Comment by blender** [comment]
Thanks @pt2121 ! Good luck!

**Comment by blender** [comment]
@pt2121 Thanks again! Do you use Rome or just wanted to contribute to some hacktoberfest Haskell project?

**Comment by pt2121** [comment]
@blender i'm doing hacktoberfest and learning Haskell. Thanks for the beginner label. Super helpful!
