### ISSUE TITLE
Support for carthage packages that have multiple framework output

### ISSUE THREAD

**Issue by ctee-cormant** [blender/Rome#80]
One of the carthage package that we use is XCGLogger and it contains two frameworks:

- ObjcExceptionBridging.framework
- XCGLogger.framework

Rome is able to upload the XCGLogger.framework and symbol files but completely ignores the ObjcExceptionBridging.framework.

    Rome version: 0.11.0.27
    OS and version: macOS 10.12.5

**Comment by blender** [comment]
Hi, thanks for opening an issue. 

This feature is already supported. Refer to https://github.com/blender/Rome#multiple-aliases

Add for your RepositoryMap the following

```
[RepositoryMap]

XCGLogger = XCGLogger, ObjcExceptionBridging
```

**Comment by ctee-cormant** [comment]
It worked! I have it now on our Xcode 9 server. Thanks @blender!
