### ISSUE TITLE
Different build paths for Xcode 8 and 9

### ISSUE THREAD

**Issue by Zeotyn** [blender/Rome#82]
Hi there,

I'm looking for an option to build and upload different xcode-version builds of the same framework into the same bucket. 

This might be possible by storing different buildtypes in subpaths in the same buckets and up-/downloading with a configuration path like:

`rome upload --buildpath DEFINED_IN_ROMEFILE`
`rome download --buildpath DEFINED_IN_ROMEFILE`

The buildpath could simply be defined within the romefile.

Does a similar feature already exist?

    **Rome version:** latest
    **OS and version:** macOS 10.12.5

Cheers

**Comment by blender** [comment]
Hi, @Zeotyn 

thanks for opining an issue.

This feature does not exist at the moment. I'm assuming that what you really want is not the Xcode Version but rather the Swift version. Is that correct?

**Comment by Zeotyn** [comment]
Sounds great! I meant Swift versions, sorry.

**Comment by blender** [comment]
@Zeotyn Please try pre-release https://github.com/blender/Rome/releases/tag/v0.12.0.29

Please report any bugs, if it works as intended I will make a full release.

**Comment by kaybutter** [comment]
The prefix doesn't seem to be consistently applied to the local cache path. It's used for lookup but the downloaded files are not copied to the right location yet:
```
▸ Error: could not find quick.dSYM in local cache at : /Users/fhqwhgads/Library/Caches/Rome/Xcode9/quick/iOS/quick.framework.dSYM-v1.1.0.zip
▸ Downloaded quick.dSYM from: Xcode9/quick/iOS/quick.framework.dSYM-v1.1.0.zip
▸ Copied quick.dSYM to: /Users/fhqwhgads/Library/Caches/Rome/quick/iOS/quick.framework.dSYM-v1.1.0.zip
```

**Comment by blender** [comment]
@kaybutter thanks, I'll check. I think it might be just a an error in the logs.

**Comment by kaybutter** [comment]
Nope. It actually overwrote the old cache, that's how I noticed.

**Comment by blender** [comment]
Good catch, 

please try https://github.com/blender/Rome/releases/tag/v0.12.0.30

**Comment by Zeotyn** [comment]
@blender great and very fast thanks!

```
▸ Error: could not find quick in local cache at : /Users/mobileadmin/Library/Caches/Rome/Xcode9/quick/iOS/quick.framework-v1.1.0.zip
▸ Downloaded quick from: Xcode9/quick/iOS/quick.framework-v1.1.0.zip
▸ Copied quick to: /Users/mobileadmin/Library/Caches/Rome/Xcode9/quick/iOS/quick.framework-v1.1.0.zip
```

**Comment by blender** [comment]
@Zeotyn @kaybutter no problem. I'll test a little more and then make a full release via `brew`

**Comment by blender** [comment]
FYI don't you that tag there is one more bug when uploading `.version` files.  Wait for the full release. It will happen shortly

**Comment by blender** [comment]
New version is out:

get it at https://github.com/blender/Rome/releases/tag/v0.12.0.31 or run `brew update rome`
