### ISSUE TITLE
Rome does not upload framework if dependency name and framework name does not match.

### ISSUE THREAD

**Issue by vgorloff** [blender/Rome#94]
#### Issue

Rome does not upload framework if dependency name and framework name does not match.
---

**Steps to reproduce**

1. Add to the `Cartfile` dependency: `github "ashleymills/Reachability.swift" == 3.0`
2. Build carthage for platform iOS. As Result you will get `Cartfile.resolved` with the contents like `github "ashleymills/Reachability.swift" "v3"`
3. Upload dependencies to S3 using Rome: `rome upload --platform iOS --cache-prefix 8E3004b`
4. Explore S3 bucket. 

**Expected**

1. Version file exists: `8E3004b/Reachability.swift/.Reachability.swift.version-v3`
2. Framework exists: `8E3004b/Reachability.swift/iOS/Reachability.framework-v3.zip`
3. dSYM file exists: `8E3004b/Reachability.swift/iOS/Reachability.framework-v3.dSYM.zip`

**Observed**
1. Version file exists: `8E3004b/Reachability.swift/.Reachability.swift.version-v3`
2. Framework and dSYM files missed.

---

**Additional info**

Before upload (and download as well) Rome should read contents of version file `.Reachability.swift.version-v3` to get actual name of  framework.  
For instance contents of `.Reachability.swift.version-v3` is the following:

```
{
  "commitish" : "v3",
  "iOS" : [
    {
      "hash" : "d2868e98c02222b2a7bff12397406e821bf48803c701a44fb0b4667f8efd5d94",
      "name" : "Reachability"
    }
  ]
}
```

From the contents of the version file we can see that real name of framework will be "Reachability.framework", but not "Reachability.**swift**.framework".

Similar problem observed with following dependencies:

```
github "BoltsFramework/Bolts-ObjC" "1.8.4"
github "airbnb/lottie-ios" "1.0.2"
github "ashleymills/Reachability.swift" "v3"
github "facebook/facebook-ios-sdk" "sdk-version-4.21.0"
github "facebook/facebook-sdk-swift" "a09021edf33417153fdf1066275f888c3b59fc6e"
github "yeahdongcn/UIColor-Hex-Swift" "3.0.2"
```

---
**Rome version:** 0.12.0.31 - Romam uno die non fuisse conditam.
**OS and version:** macOS 10.12.5 (16F73)

Thank you!

**Comment by blender** [comment]
Hi, should be already addressed by adding name aliases in your Repository map.

For Reachability.swift specify

[RepositoryMap]
 Reachability.swift = Reachability

See https://github.com/blender/Rome#multiple-aliases

**Comment by vgorloff** [comment]
Thank you!

My bad. I did not know/read about *Multiple Aliases*.

Solution is to write `RepositoryMap` like this.

```
[RepositoryMap]
   Reachability.swift = Reachability
   Bolts-ObjC = Bolts
   lottie-ios = Lottie
   UIColor-Hex-Swift = HEXColor
   facebook-ios-sdk = FBSDKCoreKit, FBSDKLoginKit, FBSDKShareKit
   facebook-sdk-swift = FacebookCore, FacebookLogin, FacebookShare
```

**Comment by vgorloff** [comment]
I created enhancement #95. Feel free to close this issue.)

Thank you!

**Comment by blender** [comment]
@vgorloff Thanks! I will updated the documentation to make the Multiple Aliases more obvious.
